load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "spellcheck",
    srcs = [
        "icu.go",
        "markup.go",
    ],
    importpath = "github.com/hyperlocalise/hyperlocalise/internal/i18n/spellcheck",
    visibility = ["//visibility:public"],
    deps = ["//internal/i18n/icuparser"],
)

go_test(
    name = "spellcheck_test",
    srcs = [
        "icu_test.go",
        "markup_test.go",
    ],
    embed = [":spellcheck"],
)
