go_library(
    name = "memoryinterchange",
    srcs = [
        "import_plan.go",
        "interchange.go",
        "testdata.go",
    ],
    embedsrcs = glob(["testdata/**"]),
    importpath = "github.com/hyperlocalise/hyperlocalise/internal/i18n/memoryinterchange",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/i18n/editor-export:editor-export",
        "@org_golang_x_text//language",
        "@org_golang_x_text//unicode/norm",
    ],
)
