package memoryinterchange

import (
	"strings"
	"testing"
)

func TestParseTMXUsesHeaderSourceAndTuidKeys(t *testing.T) {
	content := `<?xml version="1.0"?><tmx version="1.4"><header srclang="en-US"/><body><tu tuid="one"><tuv xml:lang="fr-FR"><seg>Bonjour</seg></tuv><tuv xml:lang="en-US"><seg>Hello</seg></tuv></tu></body></tmx>`
	candidates, issues, header, err := Parse("tmx", content)
	if err != nil || len(issues) != 0 || header == nil || len(candidates) != 1 {
		t.Fatalf("Parse() = candidates=%d issues=%d header=%v err=%v", len(candidates), len(issues), header, err)
	}
	if candidates[0].SourceLocale != "en-US" || candidates[0].TargetLocale != "fr-FR" || candidates[0].SourceText != "Hello" || candidates[0].TargetText != "Bonjour" {
		t.Fatalf("unexpected candidate: %+v", candidates[0])
	}
	if candidates[0].ExternalKey == nil || *candidates[0].ExternalKey != "tmx:one:fr-FR" {
		t.Fatalf("unexpected external key: %v", candidates[0].ExternalKey)
	}
}

func TestCSVFormulaRoundTrip(t *testing.T) {
	rows := []Candidate{{SourceLocale: "en-US", TargetLocale: "fr-FR", SourceText: "=SUM(A1)", TargetText: "@mention", MatchScore: 100}}
	body, err := SerializeCSV(rows)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), FormulaEscapePrefix+"=SUM(A1)") {
		t.Fatalf("formula was not escaped: %s", body)
	}
	parsed := ParseCSV(string(body))
	if len(parsed) != 1 || parsed[0].SourceText != "=SUM(A1)" || parsed[0].TargetText != "@mention" {
		t.Fatalf("CSV round trip failed: %+v", parsed)
	}
}

func TestParseInvalidTMXReportsIssue(t *testing.T) {
	_, issues, _, err := Parse("tmx", "<not-xml")
	if err != nil || len(issues) != 1 || issues[0].Code != "invalid_tmx" {
		t.Fatalf("unexpected invalid TMX result: issues=%+v err=%v", issues, err)
	}
}

func TestNormalizeSourceText(t *testing.T) {
	if got := NormalizeSourceText("  Ａ  B\tC  "); got != "a b c" {
		t.Fatalf("NormalizeSourceText() = %q, want %q", got, "a b c")
	}
}

func TestParseCSV_RejectsGenericSourceTargetHeader(t *testing.T) {
	csv := "source,target\nHello,Bonjour\n"
	if candidates := ParseCSV(csv); len(candidates) != 0 {
		t.Fatalf("ParseCSV() len = %d, want 0 for non-locale header", len(candidates))
	}
}

func TestParseCSV_CrowdinTwoColumnFixture(t *testing.T) {
	candidates := ParseCSV(string(ReadTestdata(t, "crowdin-two-column.csv")))
	if len(candidates) != 2 {
		t.Fatalf("ParseCSV() len = %d, want 2", len(candidates))
	}
	if candidates[0].SourceLocale != "en" || candidates[0].TargetLocale != "vi" {
		t.Fatalf("unexpected locales: %+v", candidates[0])
	}
	if candidates[0].SourceText != "Discount" || candidates[0].TargetText != "Khuyến mãi" {
		t.Fatalf("unexpected first row: %+v", candidates[0])
	}
}

func TestParseTMX_CrowdinWithPropFixture(t *testing.T) {
	candidates, issues, header, err := Parse("tmx", string(ReadTestdata(t, "crowdin-with-prop.tmx")))
	if err != nil || len(issues) != 0 || header == nil || *header != "en" {
		t.Fatalf("Parse() = candidates=%d issues=%d header=%v err=%v", len(candidates), len(issues), header, err)
	}
	if len(candidates) != 2 {
		t.Fatalf("Parse() len = %d, want 2", len(candidates))
	}
	if candidates[0].ExternalKey == nil || *candidates[0].ExternalKey != "tmx:eccbc87e4b5ce2fe28308fd9f2a7baf33:vi" {
		t.Fatalf("unexpected external key: %v", candidates[0].ExternalKey)
	}
}

func TestSerializeTMX_ThenParse_RoundTripHLMDPH(t *testing.T) {
	const token = "\x1eHLMDPH_8E6DFE8F53EA_0\x1f"
	row := Candidate{
		SourceLocale: "en-US", TargetLocale: "fr-FR",
		SourceText: "Agents" + token + " automation", TargetText: "Agents et automatisation",
		MatchScore: 100, UnitIndex: 1,
	}
	tmx := string(SerializeTMX([]Candidate{row}))
	if !strings.Contains(tmx, "<!--Generated by hyperlocalise.com-->") {
		t.Fatalf("missing generator comment in export")
	}
	candidates, issues, _, err := Parse("tmx", tmx)
	if err != nil || len(issues) != 0 {
		t.Fatalf("Parse() issues=%+v err=%v", issues, err)
	}
	if len(candidates) != 1 {
		t.Fatalf("Parse() len = %d, want 1", len(candidates))
	}
	if strings.Contains(candidates[0].SourceText, "\x1e") {
		t.Fatalf("expected control chars stripped from export, got %q", candidates[0].SourceText)
	}
	if strings.Contains(candidates[0].SourceText, "HLMDPH_") {
		t.Fatalf("expected internal placeholder removed from export, got %q", candidates[0].SourceText)
	}
}
