/*
 * Copyright (c) 2026 Hyperlocalise Pty Ltd
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in this application's LICENSE file.
 *
 * Change Date: Four years after publication of the applicable version.
 *
 * On the Change Date, in accordance with the Business Source License, use
 * of this software will be governed by the GNU General Public License
 * Version 2.0 or later.
 */

export type CrowdinGlossaryLanguage = {
  id: string;
  name: string;
  editorCode: string;
  twoLettersCode: string;
  threeLettersCode: string;
  locale: string;
  androidCode: string;
  bcp47Code: string;
  osxCode: string;
  osxLocale: string;
  dialectOf: string | null;
};

/**
 * Complete built-in Crowdin language catalog from GET /api/v2/languages.
 *
 * Crowdin uses language IDs for glossary API payloads while Hyperlocalise
 * uses BCP-47 locales in its glossary contract. Custom languages are not
 * included by Crowdin's language catalog endpoint.
 */
export const CROWDIN_GLOSSARY_LANGUAGES = [
  {
    id: "ach",
    name: "Acholi",
    editorCode: "ach",
    twoLettersCode: "ach",
    threeLettersCode: "ach",
    locale: "ach-UG",
    androidCode: "ach-rUG",
    bcp47Code: "b+ach+UG",
    osxCode: "ach.lproj",
    osxLocale: "ach",
    dialectOf: null,
  },
  {
    id: "aa",
    name: "Afar",
    editorCode: "aa",
    twoLettersCode: "aa",
    threeLettersCode: "aar",
    locale: "aa-ER",
    androidCode: "aa-rER",
    bcp47Code: "b+aa+ER",
    osxCode: "aa.lproj",
    osxLocale: "aa",
    dialectOf: null,
  },
  {
    id: "af",
    name: "Afrikaans",
    editorCode: "af",
    twoLettersCode: "af",
    threeLettersCode: "afr",
    locale: "af-ZA",
    androidCode: "af-rZA",
    bcp47Code: "b+af+ZA",
    osxCode: "af.lproj",
    osxLocale: "af",
    dialectOf: null,
  },
  {
    id: "ak",
    name: "Akan",
    editorCode: "ak",
    twoLettersCode: "ak",
    threeLettersCode: "aka",
    locale: "ak-GH",
    androidCode: "ak-rGH",
    bcp47Code: "b+ak+GH",
    osxCode: "ak.lproj",
    osxLocale: "ak",
    dialectOf: null,
  },
  {
    id: "tw",
    name: "Akan, Twi",
    editorCode: "tw",
    twoLettersCode: "tw",
    threeLettersCode: "twi",
    locale: "tw-TW",
    androidCode: "tw-rTW",
    bcp47Code: "b+tw+TW",
    osxCode: "tw.lproj",
    osxLocale: "tw",
    dialectOf: "ak",
  },
  {
    id: "sq",
    name: "Albanian",
    editorCode: "sq",
    twoLettersCode: "sq",
    threeLettersCode: "sqi",
    locale: "sq-AL",
    androidCode: "sq-rAL",
    bcp47Code: "b+sq+AL",
    osxCode: "sq.lproj",
    osxLocale: "sq",
    dialectOf: null,
  },
  {
    id: "am",
    name: "Amharic",
    editorCode: "am",
    twoLettersCode: "am",
    threeLettersCode: "amh",
    locale: "am-ET",
    androidCode: "am-rET",
    bcp47Code: "b+am+ET",
    osxCode: "am.lproj",
    osxLocale: "am",
    dialectOf: null,
  },
  {
    id: "ar",
    name: "Arabic",
    editorCode: "ar",
    twoLettersCode: "ar",
    threeLettersCode: "ara",
    locale: "ar-SA",
    androidCode: "ar-rSA",
    bcp47Code: "b+ar+SA",
    osxCode: "ar.lproj",
    osxLocale: "ar",
    dialectOf: null,
  },
  {
    id: "ar-BH",
    name: "Arabic, Bahrain",
    editorCode: "arbh",
    twoLettersCode: "ar",
    threeLettersCode: "ara",
    locale: "ar-BH",
    androidCode: "ar-rBH",
    bcp47Code: "b+ar+BH",
    osxCode: "ar-BH.lproj",
    osxLocale: "ar_BH",
    dialectOf: "ar",
  },
  {
    id: "ar-EG",
    name: "Arabic, Egypt",
    editorCode: "areg",
    twoLettersCode: "ar",
    threeLettersCode: "ara",
    locale: "ar-EG",
    androidCode: "ar-rEG",
    bcp47Code: "b+ar+EG",
    osxCode: "ar-EG.lproj",
    osxLocale: "ar_EG",
    dialectOf: "ar",
  },
  {
    id: "ar-SA",
    name: "Arabic, Saudi Arabia",
    editorCode: "arsa",
    twoLettersCode: "ar",
    threeLettersCode: "ara",
    locale: "ar-SA",
    androidCode: "ar-rSA",
    bcp47Code: "b+ar+SA",
    osxCode: "ar-SA.lproj",
    osxLocale: "ar_SA",
    dialectOf: "ar",
  },
  {
    id: "ar-YE",
    name: "Arabic, Yemen",
    editorCode: "arye",
    twoLettersCode: "ar",
    threeLettersCode: "ara",
    locale: "ar-YE",
    androidCode: "ar-rYE",
    bcp47Code: "b+ar+YE",
    osxCode: "ar-YE.lproj",
    osxLocale: "ar_YE",
    dialectOf: "ar",
  },
  {
    id: "an",
    name: "Aragonese",
    editorCode: "an",
    twoLettersCode: "an",
    threeLettersCode: "arg",
    locale: "an-ES",
    androidCode: "an-rES",
    bcp47Code: "b+an+ES",
    osxCode: "an.lproj",
    osxLocale: "an",
    dialectOf: null,
  },
  {
    id: "hy-AM",
    name: "Armenian",
    editorCode: "hy",
    twoLettersCode: "hy",
    threeLettersCode: "hye",
    locale: "hy-AM",
    androidCode: "hy-rAM",
    bcp47Code: "b+hy+AM",
    osxCode: "hy.lproj",
    osxLocale: "hy",
    dialectOf: null,
  },
  {
    id: "frp",
    name: "Arpitan",
    editorCode: "frp",
    twoLettersCode: "frp",
    threeLettersCode: "frp",
    locale: "frp-IT",
    androidCode: "frp-rIT",
    bcp47Code: "b+frp+IT",
    osxCode: "frp.lproj",
    osxLocale: "frp",
    dialectOf: null,
  },
  {
    id: "as",
    name: "Assamese",
    editorCode: "as",
    twoLettersCode: "as",
    threeLettersCode: "asm",
    locale: "as-IN",
    androidCode: "as-rIN",
    bcp47Code: "b+as+IN",
    osxCode: "as.lproj",
    osxLocale: "as",
    dialectOf: null,
  },
  {
    id: "ast",
    name: "Asturian",
    editorCode: "ast",
    twoLettersCode: "ast",
    threeLettersCode: "ast",
    locale: "ast-ES",
    androidCode: "ast-rES",
    bcp47Code: "b+ast+ES",
    osxCode: "ast.lproj",
    osxLocale: "ast",
    dialectOf: null,
  },
  {
    id: "tay",
    name: "Atayal",
    editorCode: "tay",
    twoLettersCode: "tay",
    threeLettersCode: "tay",
    locale: "tay-TW",
    androidCode: "tay-rTW",
    bcp47Code: "b+tay+TW",
    osxCode: "tay.lproj",
    osxLocale: "tay",
    dialectOf: null,
  },
  {
    id: "av",
    name: "Avaric",
    editorCode: "av",
    twoLettersCode: "av",
    threeLettersCode: "ava",
    locale: "av-DA",
    androidCode: "av-rDA",
    bcp47Code: "b+av+DA",
    osxCode: "av.lproj",
    osxLocale: "av",
    dialectOf: null,
  },
  {
    id: "ae",
    name: "Avestan",
    editorCode: "ae",
    twoLettersCode: "ae",
    threeLettersCode: "ave",
    locale: "ae-IR",
    androidCode: "ae-rIR",
    bcp47Code: "b+ae+IR",
    osxCode: "ae.lproj",
    osxLocale: "ae",
    dialectOf: null,
  },
  {
    id: "ay",
    name: "Aymara",
    editorCode: "ay",
    twoLettersCode: "ay",
    threeLettersCode: "aym",
    locale: "ay-BO",
    androidCode: "ay-rBO",
    bcp47Code: "b+ay+BO",
    osxCode: "ay.lproj",
    osxLocale: "ay",
    dialectOf: null,
  },
  {
    id: "az",
    name: "Azerbaijani",
    editorCode: "az",
    twoLettersCode: "az",
    threeLettersCode: "aze",
    locale: "az-AZ",
    androidCode: "az-rAZ",
    bcp47Code: "b+az+AZ",
    osxCode: "az.lproj",
    osxLocale: "az",
    dialectOf: null,
  },
  {
    id: "ban",
    name: "Balinese",
    editorCode: "ban",
    twoLettersCode: "ban",
    threeLettersCode: "ban",
    locale: "ban-ID",
    androidCode: "ban-rID",
    bcp47Code: "b+ban+ID",
    osxCode: "ban.lproj",
    osxLocale: "ban",
    dialectOf: null,
  },
  {
    id: "bal",
    name: "Balochi",
    editorCode: "bal",
    twoLettersCode: "bal",
    threeLettersCode: "bal",
    locale: "bal-BA",
    androidCode: "bal-rBA",
    bcp47Code: "b+bal+BA",
    osxCode: "bal.lproj",
    osxLocale: "bal",
    dialectOf: null,
  },
  {
    id: "bm",
    name: "Bambara",
    editorCode: "bm",
    twoLettersCode: "bm",
    threeLettersCode: "bam",
    locale: "bm-ML",
    androidCode: "bm-rML",
    bcp47Code: "b+bm+ML",
    osxCode: "bm.lproj",
    osxLocale: "bm",
    dialectOf: null,
  },
  {
    id: "ba",
    name: "Bashkir",
    editorCode: "ba",
    twoLettersCode: "ba",
    threeLettersCode: "bak",
    locale: "ba-RU",
    androidCode: "ba-rRU",
    bcp47Code: "b+ba+RU",
    osxCode: "ba.lproj",
    osxLocale: "ba",
    dialectOf: null,
  },
  {
    id: "eu",
    name: "Basque",
    editorCode: "eu",
    twoLettersCode: "eu",
    threeLettersCode: "eus",
    locale: "eu-ES",
    androidCode: "eu-rES",
    bcp47Code: "b+eu+ES",
    osxCode: "eu.lproj",
    osxLocale: "eu",
    dialectOf: null,
  },
  {
    id: "be",
    name: "Belarusian",
    editorCode: "be",
    twoLettersCode: "be",
    threeLettersCode: "bel",
    locale: "be-BY",
    androidCode: "be-rBY",
    bcp47Code: "b+be+BY",
    osxCode: "be.lproj",
    osxLocale: "be",
    dialectOf: null,
  },
  {
    id: "bn",
    name: "Bengali",
    editorCode: "bn",
    twoLettersCode: "bn",
    threeLettersCode: "ben",
    locale: "bn-BD",
    androidCode: "bn-rBD",
    bcp47Code: "b+bn+BD",
    osxCode: "bn.lproj",
    osxLocale: "bn",
    dialectOf: null,
  },
  {
    id: "bn-IN",
    name: "Bengali, India",
    editorCode: "bnin",
    twoLettersCode: "bn",
    threeLettersCode: "ben",
    locale: "bn-IN",
    androidCode: "bn-rIN",
    bcp47Code: "b+bn+IN",
    osxCode: "bn-IN.lproj",
    osxLocale: "bn_IN",
    dialectOf: "bn",
  },
  {
    id: "ber",
    name: "Berber",
    editorCode: "ber",
    twoLettersCode: "ber",
    threeLettersCode: "ber",
    locale: "ber-DZ",
    androidCode: "ber-rDZ",
    bcp47Code: "b+ber+DZ",
    osxCode: "ber.lproj",
    osxLocale: "ber",
    dialectOf: null,
  },
  {
    id: "bh",
    name: "Bihari",
    editorCode: "bh",
    twoLettersCode: "bh",
    threeLettersCode: "bih",
    locale: "bh-IN",
    androidCode: "bh-rIN",
    bcp47Code: "b+bh+IN",
    osxCode: "bh.lproj",
    osxLocale: "bh",
    dialectOf: null,
  },
  {
    id: "bfo",
    name: "Birifor",
    editorCode: "bfo",
    twoLettersCode: "bfo",
    threeLettersCode: "bfo",
    locale: "bfo-BF",
    androidCode: "bfo-rBF",
    bcp47Code: "b+bfo+BF",
    osxCode: "bfo.lproj",
    osxLocale: "bfo",
    dialectOf: null,
  },
  {
    id: "bi",
    name: "Bislama",
    editorCode: "bi",
    twoLettersCode: "bi",
    threeLettersCode: "bis",
    locale: "bi-VU",
    androidCode: "bi-rVU",
    bcp47Code: "b+bi+VU",
    osxCode: "bi.lproj",
    osxLocale: "bi",
    dialectOf: null,
  },
  {
    id: "bs",
    name: "Bosnian",
    editorCode: "bs",
    twoLettersCode: "bs",
    threeLettersCode: "bos",
    locale: "bs-BA",
    androidCode: "bs-rBA",
    bcp47Code: "b+bs+BA",
    osxCode: "bs.lproj",
    osxLocale: "bs",
    dialectOf: null,
  },
  {
    id: "br-FR",
    name: "Breton",
    editorCode: "brfr",
    twoLettersCode: "br",
    threeLettersCode: "bre",
    locale: "br-FR",
    androidCode: "br-rFR",
    bcp47Code: "b+br+FR",
    osxCode: "br.lproj",
    osxLocale: "br",
    dialectOf: null,
  },
  {
    id: "bg",
    name: "Bulgarian",
    editorCode: "bg",
    twoLettersCode: "bg",
    threeLettersCode: "bul",
    locale: "bg-BG",
    androidCode: "bg-rBG",
    bcp47Code: "b+bg+BG",
    osxCode: "bg.lproj",
    osxLocale: "bg",
    dialectOf: null,
  },
  {
    id: "my",
    name: "Burmese",
    editorCode: "my",
    twoLettersCode: "my",
    threeLettersCode: "mya",
    locale: "my-MM",
    androidCode: "my-rMM",
    bcp47Code: "b+my+MM",
    osxCode: "my.lproj",
    osxLocale: "my",
    dialectOf: null,
  },
  {
    id: "ca",
    name: "Catalan",
    editorCode: "ca",
    twoLettersCode: "ca",
    threeLettersCode: "cat",
    locale: "ca-ES",
    androidCode: "ca-rES",
    bcp47Code: "b+ca+ES",
    osxCode: "ca.lproj",
    osxLocale: "ca",
    dialectOf: null,
  },
  {
    id: "ceb",
    name: "Cebuano",
    editorCode: "ceb",
    twoLettersCode: "ceb",
    threeLettersCode: "ceb",
    locale: "ceb-PH",
    androidCode: "ceb-rPH",
    bcp47Code: "b+ceb+PH",
    osxCode: "ceb.lproj",
    osxLocale: "ceb",
    dialectOf: null,
  },
  {
    id: "ch",
    name: "Chamorro",
    editorCode: "ch",
    twoLettersCode: "ch",
    threeLettersCode: "cha",
    locale: "ch-GU",
    androidCode: "ch-rGU",
    bcp47Code: "b+ch+GU",
    osxCode: "ch.lproj",
    osxLocale: "ch",
    dialectOf: null,
  },
  {
    id: "ce",
    name: "Chechen",
    editorCode: "ce",
    twoLettersCode: "ce",
    threeLettersCode: "che",
    locale: "ce-CE",
    androidCode: "ce-rCE",
    bcp47Code: "b+ce+CE",
    osxCode: "ce.lproj",
    osxLocale: "ce",
    dialectOf: null,
  },
  {
    id: "chr",
    name: "Cherokee",
    editorCode: "chr",
    twoLettersCode: "chr",
    threeLettersCode: "chr",
    locale: "chr-US",
    androidCode: "chr-rUS",
    bcp47Code: "b+chr+US",
    osxCode: "chr.lproj",
    osxLocale: "chr",
    dialectOf: null,
  },
  {
    id: "ny",
    name: "Chewa",
    editorCode: "ny",
    twoLettersCode: "ny",
    threeLettersCode: "nya",
    locale: "ny-MW",
    androidCode: "ny-rMW",
    bcp47Code: "b+ny+MW",
    osxCode: "ny.lproj",
    osxLocale: "ny",
    dialectOf: null,
  },
  {
    id: "zh-CN",
    name: "Chinese Simplified",
    editorCode: "zhcn",
    twoLettersCode: "zh",
    threeLettersCode: "zho",
    locale: "zh-CN",
    androidCode: "zh-rCN",
    bcp47Code: "b+zh+Hans",
    osxCode: "zh-Hans.lproj",
    osxLocale: "zh-Hans",
    dialectOf: null,
  },
  {
    id: "zh-SG",
    name: "Chinese Simplified, Singapore",
    editorCode: "zhsg",
    twoLettersCode: "zh",
    threeLettersCode: "zho",
    locale: "zh-SG",
    androidCode: "zh-rSG",
    bcp47Code: "b+zh+Hans+SG",
    osxCode: "zh-SG.lproj",
    osxLocale: "zh_SG",
    dialectOf: "zh-CN",
  },
  {
    id: "zh-TW",
    name: "Chinese Traditional",
    editorCode: "zhtw",
    twoLettersCode: "zh",
    threeLettersCode: "zho",
    locale: "zh-TW",
    androidCode: "zh-rTW",
    bcp47Code: "b+zh+Hant",
    osxCode: "zh-Hant.lproj",
    osxLocale: "zh-Hant",
    dialectOf: null,
  },
  {
    id: "zh-HK",
    name: "Chinese Traditional, Hong Kong",
    editorCode: "zhhk",
    twoLettersCode: "zh",
    threeLettersCode: "zho",
    locale: "zh-HK",
    androidCode: "zh-rHK",
    bcp47Code: "b+zh+Hant+HK",
    osxCode: "zh-HK.lproj",
    osxLocale: "zh_HK",
    dialectOf: null,
  },
  {
    id: "zh-MO",
    name: "Chinese Traditional, Macau",
    editorCode: "zhmo",
    twoLettersCode: "zh",
    threeLettersCode: "zho",
    locale: "zh-MO",
    androidCode: "zh-rMO",
    bcp47Code: "b+zh+Hant+MO",
    osxCode: "zh-MO.lproj",
    osxLocale: "zh_MO",
    dialectOf: "zh-TW",
  },
  {
    id: "cv",
    name: "Chuvash",
    editorCode: "cv",
    twoLettersCode: "cv",
    threeLettersCode: "chv",
    locale: "cv-CU",
    androidCode: "cv-rCU",
    bcp47Code: "b+cv+CU",
    osxCode: "cv.lproj",
    osxLocale: "cv",
    dialectOf: null,
  },
  {
    id: "kw",
    name: "Cornish",
    editorCode: "kw",
    twoLettersCode: "kw",
    threeLettersCode: "cor",
    locale: "kw-GB",
    androidCode: "kw-rGB",
    bcp47Code: "b+kw+GB",
    osxCode: "kw.lproj",
    osxLocale: "kw",
    dialectOf: null,
  },
  {
    id: "co",
    name: "Corsican",
    editorCode: "co",
    twoLettersCode: "co",
    threeLettersCode: "cos",
    locale: "co-FR",
    androidCode: "co-rFR",
    bcp47Code: "b+co+FR",
    osxCode: "co.lproj",
    osxLocale: "co",
    dialectOf: null,
  },
  {
    id: "cr",
    name: "Cree",
    editorCode: "cr",
    twoLettersCode: "cr",
    threeLettersCode: "cre",
    locale: "cr-NT",
    androidCode: "cr-rNT",
    bcp47Code: "b+cr+NT",
    osxCode: "cr.lproj",
    osxLocale: "cr",
    dialectOf: null,
  },
  {
    id: "hr",
    name: "Croatian",
    editorCode: "hr",
    twoLettersCode: "hr",
    threeLettersCode: "hrv",
    locale: "hr-HR",
    androidCode: "hr-rHR",
    bcp47Code: "b+hr+HR",
    osxCode: "hr.lproj",
    osxLocale: "hr",
    dialectOf: null,
  },
  {
    id: "cs",
    name: "Czech",
    editorCode: "cs",
    twoLettersCode: "cs",
    threeLettersCode: "ces",
    locale: "cs-CZ",
    androidCode: "cs-rCZ",
    bcp47Code: "b+cs+CZ",
    osxCode: "cs.lproj",
    osxLocale: "cs",
    dialectOf: null,
  },
  {
    id: "da",
    name: "Danish",
    editorCode: "da",
    twoLettersCode: "da",
    threeLettersCode: "dan",
    locale: "da-DK",
    androidCode: "da-rDK",
    bcp47Code: "b+da+DK",
    osxCode: "da.lproj",
    osxLocale: "da",
    dialectOf: null,
  },
  {
    id: "fa-AF",
    name: "Dari",
    editorCode: "faaf",
    twoLettersCode: "fa",
    threeLettersCode: "prs",
    locale: "fa-AF",
    androidCode: "fa-rAF",
    bcp47Code: "b+fa+AF",
    osxCode: "fa-AF.lproj",
    osxLocale: "fa_AF",
    dialectOf: null,
  },
  {
    id: "dv",
    name: "Dhivehi",
    editorCode: "dv",
    twoLettersCode: "dv",
    threeLettersCode: "div",
    locale: "dv-MV",
    androidCode: "dv-rMV",
    bcp47Code: "b+dv+MV",
    osxCode: "dv.lproj",
    osxLocale: "dv",
    dialectOf: null,
  },
  {
    id: "nl",
    name: "Dutch",
    editorCode: "nl",
    twoLettersCode: "nl",
    threeLettersCode: "nld",
    locale: "nl-NL",
    androidCode: "nl-rNL",
    bcp47Code: "b+nl+NL",
    osxCode: "nl.lproj",
    osxLocale: "nl",
    dialectOf: null,
  },
  {
    id: "nl-BE",
    name: "Dutch, Belgium",
    editorCode: "nlbe",
    twoLettersCode: "nl",
    threeLettersCode: "nld",
    locale: "nl-BE",
    androidCode: "nl-rBE",
    bcp47Code: "b+nl+BE",
    osxCode: "nl-BE.lproj",
    osxLocale: "nl_BE",
    dialectOf: "nl",
  },
  {
    id: "nl-SR",
    name: "Dutch, Suriname",
    editorCode: "nlsr",
    twoLettersCode: "nl",
    threeLettersCode: "nld",
    locale: "nl-SR",
    androidCode: "nl-rSR",
    bcp47Code: "b+nl+SR",
    osxCode: "nl-SR.lproj",
    osxLocale: "nl_SR",
    dialectOf: "nl",
  },
  {
    id: "dz",
    name: "Dzongkha",
    editorCode: "dz",
    twoLettersCode: "dz",
    threeLettersCode: "dzo",
    locale: "dz-BT",
    androidCode: "dz-rBT",
    bcp47Code: "b+dz+BT",
    osxCode: "dz.lproj",
    osxLocale: "dz",
    dialectOf: null,
  },
  {
    id: "en",
    name: "English",
    editorCode: "en",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-US",
    androidCode: "en-rUS",
    bcp47Code: "b+en+US",
    osxCode: "en.lproj",
    osxLocale: "en",
    dialectOf: null,
  },
  {
    id: "en-UD",
    name: "English (upside down)",
    editorCode: "enud",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-UD",
    androidCode: "en-rUD",
    bcp47Code: "b+en+UD",
    osxCode: "en-UD.lproj",
    osxLocale: "en_UD",
    dialectOf: null,
  },
  {
    id: "en-AR",
    name: "English, Arabia",
    editorCode: "enar",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-AR",
    androidCode: "en-rAR",
    bcp47Code: "b+en+AR",
    osxCode: "en-AR.lproj",
    osxLocale: "en_AR",
    dialectOf: "en",
  },
  {
    id: "en-AU",
    name: "English, Australia",
    editorCode: "enau",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-AU",
    androidCode: "en-rAU",
    bcp47Code: "b+en+AU",
    osxCode: "en-AU.lproj",
    osxLocale: "en_AU",
    dialectOf: "en",
  },
  {
    id: "en-BZ",
    name: "English, Belize",
    editorCode: "enbz",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-BZ",
    androidCode: "en-rBZ",
    bcp47Code: "b+en+BZ",
    osxCode: "en-BZ.lproj",
    osxLocale: "en_BZ",
    dialectOf: "en",
  },
  {
    id: "en-CA",
    name: "English, Canada",
    editorCode: "enca",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-CA",
    androidCode: "en-rCA",
    bcp47Code: "b+en+CA",
    osxCode: "en-CA.lproj",
    osxLocale: "en_CA",
    dialectOf: "en",
  },
  {
    id: "en-CB",
    name: "English, Caribbean",
    editorCode: "encb",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-CB",
    androidCode: "en-rCB",
    bcp47Code: "b+en+CB",
    osxCode: "en-CB.lproj",
    osxLocale: "en_CB",
    dialectOf: "en",
  },
  {
    id: "en-CN",
    name: "English, China",
    editorCode: "encn",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-CN",
    androidCode: "en-rCN",
    bcp47Code: "b+en+CN",
    osxCode: "en-CN.lproj",
    osxLocale: "en_CN",
    dialectOf: "en",
  },
  {
    id: "en-DK",
    name: "English, Denmark",
    editorCode: "endk",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-DK",
    androidCode: "en-rDK",
    bcp47Code: "b+en+DK",
    osxCode: "en-DK.lproj",
    osxLocale: "en_DK",
    dialectOf: "en",
  },
  {
    id: "en-HK",
    name: "English, Hong Kong",
    editorCode: "enhk",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-HK",
    androidCode: "en-rHK",
    bcp47Code: "b+en+HK",
    osxCode: "en-HK.lproj",
    osxLocale: "en_HK",
    dialectOf: "en",
  },
  {
    id: "en-IN",
    name: "English, India",
    editorCode: "enin",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-IN",
    androidCode: "en-rIN",
    bcp47Code: "b+en+IN",
    osxCode: "en-IN.lproj",
    osxLocale: "en_IN",
    dialectOf: "en",
  },
  {
    id: "en-ID",
    name: "English, Indonesia",
    editorCode: "enid",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-ID",
    androidCode: "en-rID",
    bcp47Code: "b+en+ID",
    osxCode: "en-ID.lproj",
    osxLocale: "en_ID",
    dialectOf: "en",
  },
  {
    id: "en-IE",
    name: "English, Ireland",
    editorCode: "enie",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-IE",
    androidCode: "en-rIE",
    bcp47Code: "b+en+IE",
    osxCode: "en-IE.lproj",
    osxLocale: "en_IE",
    dialectOf: "en",
  },
  {
    id: "en-JM",
    name: "English, Jamaica",
    editorCode: "enjm",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-JM",
    androidCode: "en-rJM",
    bcp47Code: "b+en+JM",
    osxCode: "en-JM.lproj",
    osxLocale: "en_JM",
    dialectOf: "en",
  },
  {
    id: "en-JA",
    name: "English, Japan",
    editorCode: "enja",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-JA",
    androidCode: "en-rJA",
    bcp47Code: "b+en+JA",
    osxCode: "en-JA.lproj",
    osxLocale: "en_JA",
    dialectOf: "en",
  },
  {
    id: "en-MY",
    name: "English, Malaysia",
    editorCode: "enmy",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-MY",
    androidCode: "en-rMY",
    bcp47Code: "b+en+MY",
    osxCode: "en-MY.lproj",
    osxLocale: "en_MY",
    dialectOf: "en",
  },
  {
    id: "en-NZ",
    name: "English, New Zealand",
    editorCode: "ennz",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-NZ",
    androidCode: "en-rNZ",
    bcp47Code: "b+en+NZ",
    osxCode: "en-NZ.lproj",
    osxLocale: "en_NZ",
    dialectOf: "en",
  },
  {
    id: "en-NO",
    name: "English, Norway",
    editorCode: "enno",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-NO",
    androidCode: "en-rNO",
    bcp47Code: "b+en+NO",
    osxCode: "en-NO.lproj",
    osxLocale: "en_NO",
    dialectOf: "en",
  },
  {
    id: "en-PH",
    name: "English, Philippines",
    editorCode: "enph",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-PH",
    androidCode: "en-rPH",
    bcp47Code: "b+en+PH",
    osxCode: "en-PH.lproj",
    osxLocale: "en_PH",
    dialectOf: "en",
  },
  {
    id: "en-PR",
    name: "English, Puerto Rico",
    editorCode: "enpr",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-PR",
    androidCode: "en-rPR",
    bcp47Code: "b+en+PR",
    osxCode: "en-PR.lproj",
    osxLocale: "en_PR",
    dialectOf: "en",
  },
  {
    id: "en-SG",
    name: "English, Singapore",
    editorCode: "ensg",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-SG",
    androidCode: "en-rSG",
    bcp47Code: "b+en+SG",
    osxCode: "en-SG.lproj",
    osxLocale: "en_SG",
    dialectOf: "en",
  },
  {
    id: "en-ZA",
    name: "English, South Africa",
    editorCode: "enza",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-ZA",
    androidCode: "en-rZA",
    bcp47Code: "b+en+ZA",
    osxCode: "en-ZA.lproj",
    osxLocale: "en_ZA",
    dialectOf: "en",
  },
  {
    id: "en-SE",
    name: "English, Sweden",
    editorCode: "ense",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-SE",
    androidCode: "en-rSE",
    bcp47Code: "b+en+SE",
    osxCode: "en-SE.lproj",
    osxLocale: "en_SE",
    dialectOf: "en",
  },
  {
    id: "en-GB",
    name: "English, United Kingdom",
    editorCode: "engb",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-GB",
    androidCode: "en-rGB",
    bcp47Code: "b+en+GB",
    osxCode: "en-GB.lproj",
    osxLocale: "en_GB",
    dialectOf: "en",
  },
  {
    id: "en-US",
    name: "English, United States",
    editorCode: "enus",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-US",
    androidCode: "en-rUS",
    bcp47Code: "b+en+US",
    osxCode: "en-US.lproj",
    osxLocale: "en_US",
    dialectOf: "en",
  },
  {
    id: "en-ZW",
    name: "English, Zimbabwe",
    editorCode: "enzw",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-ZW",
    androidCode: "en-rZW",
    bcp47Code: "b+en+ZW",
    osxCode: "en-ZW.lproj",
    osxLocale: "en_ZW",
    dialectOf: "en",
  },
  {
    id: "eo",
    name: "Esperanto",
    editorCode: "eo",
    twoLettersCode: "eo",
    threeLettersCode: "epo",
    locale: "eo-UY",
    androidCode: "eo-rUY",
    bcp47Code: "b+eo+UY",
    osxCode: "eo.lproj",
    osxLocale: "eo",
    dialectOf: null,
  },
  {
    id: "et",
    name: "Estonian",
    editorCode: "et",
    twoLettersCode: "et",
    threeLettersCode: "est",
    locale: "et-EE",
    androidCode: "et-rEE",
    bcp47Code: "b+et+EE",
    osxCode: "et.lproj",
    osxLocale: "et",
    dialectOf: null,
  },
  {
    id: "ee",
    name: "Ewe",
    editorCode: "ee",
    twoLettersCode: "ee",
    threeLettersCode: "ewe",
    locale: "ee-GH",
    androidCode: "ee-rGH",
    bcp47Code: "b+ee+GH",
    osxCode: "ee.lproj",
    osxLocale: "ee",
    dialectOf: null,
  },
  {
    id: "fo",
    name: "Faroese",
    editorCode: "fo",
    twoLettersCode: "fo",
    threeLettersCode: "fao",
    locale: "fo-FO",
    androidCode: "fo-rFO",
    bcp47Code: "b+fo+FO",
    osxCode: "fo.lproj",
    osxLocale: "fo",
    dialectOf: null,
  },
  {
    id: "fj",
    name: "Fijian",
    editorCode: "fj",
    twoLettersCode: "fj",
    threeLettersCode: "fij",
    locale: "fj-FJ",
    androidCode: "fj-rFJ",
    bcp47Code: "b+fj+FJ",
    osxCode: "fj.lproj",
    osxLocale: "fj",
    dialectOf: null,
  },
  {
    id: "fil",
    name: "Filipino",
    editorCode: "fil",
    twoLettersCode: "fil",
    threeLettersCode: "fil",
    locale: "fil-PH",
    androidCode: "fil-rPH",
    bcp47Code: "b+fil+PH",
    osxCode: "fil.lproj",
    osxLocale: "fil",
    dialectOf: null,
  },
  {
    id: "fi",
    name: "Finnish",
    editorCode: "fi",
    twoLettersCode: "fi",
    threeLettersCode: "fin",
    locale: "fi-FI",
    androidCode: "fi-rFI",
    bcp47Code: "b+fi+FI",
    osxCode: "fi.lproj",
    osxLocale: "fi",
    dialectOf: null,
  },
  {
    id: "vls-BE",
    name: "Flemish",
    editorCode: "vlsbe",
    twoLettersCode: "vls",
    threeLettersCode: "vls",
    locale: "vls-BE",
    androidCode: "vls-rBE",
    bcp47Code: "b+vls+BE",
    osxCode: "vls.lproj",
    osxLocale: "vls",
    dialectOf: null,
  },
  {
    id: "fra-DE",
    name: "Franconian",
    editorCode: "frade",
    twoLettersCode: "fra",
    threeLettersCode: "gem",
    locale: "fra-DE",
    androidCode: "fra-rDE",
    bcp47Code: "b+fra+DE",
    osxCode: "fra.lproj",
    osxLocale: "fra",
    dialectOf: null,
  },
  {
    id: "fr",
    name: "French",
    editorCode: "fr",
    twoLettersCode: "fr",
    threeLettersCode: "fra",
    locale: "fr-FR",
    androidCode: "fr-rFR",
    bcp47Code: "b+fr+FR",
    osxCode: "fr.lproj",
    osxLocale: "fr",
    dialectOf: null,
  },
  {
    id: "fr-BE",
    name: "French, Belgium",
    editorCode: "frbe",
    twoLettersCode: "fr",
    threeLettersCode: "fra",
    locale: "fr-BE",
    androidCode: "fr-rBE",
    bcp47Code: "b+fr+BE",
    osxCode: "fr-BE.lproj",
    osxLocale: "fr_BE",
    dialectOf: "fr",
  },
  {
    id: "fr-CA",
    name: "French, Canada",
    editorCode: "frca",
    twoLettersCode: "fr",
    threeLettersCode: "fra",
    locale: "fr-CA",
    androidCode: "fr-rCA",
    bcp47Code: "b+fr+CA",
    osxCode: "fr-CA.lproj",
    osxLocale: "fr_CA",
    dialectOf: "fr",
  },
  {
    id: "fr-LU",
    name: "French, Luxembourg",
    editorCode: "frlu",
    twoLettersCode: "fr",
    threeLettersCode: "fra",
    locale: "fr-LU",
    androidCode: "fr-rLU",
    bcp47Code: "b+fr+LU",
    osxCode: "fr-LU.lproj",
    osxLocale: "fr_LU",
    dialectOf: "fr",
  },
  {
    id: "fr-QC",
    name: "French, Quebec",
    editorCode: "frqc",
    twoLettersCode: "fr",
    threeLettersCode: "fra",
    locale: "fr-QC",
    androidCode: "fr-rQC",
    bcp47Code: "b+fr+QC",
    osxCode: "fr-QC.lproj",
    osxLocale: "fr_QC",
    dialectOf: "fr",
  },
  {
    id: "fr-CH",
    name: "French, Switzerland",
    editorCode: "frch",
    twoLettersCode: "fr",
    threeLettersCode: "fra",
    locale: "fr-CH",
    androidCode: "fr-rCH",
    bcp47Code: "b+fr+CH",
    osxCode: "fr-CH.lproj",
    osxLocale: "fr_CH",
    dialectOf: "fr",
  },
  {
    id: "fy-NL",
    name: "Frisian",
    editorCode: "fy",
    twoLettersCode: "fy",
    threeLettersCode: "fry",
    locale: "fy-NL",
    androidCode: "fy-rNL",
    bcp47Code: "b+fy+NL",
    osxCode: "fy.lproj",
    osxLocale: "fy",
    dialectOf: null,
  },
  {
    id: "fur-IT",
    name: "Friulian",
    editorCode: "furit",
    twoLettersCode: "fur",
    threeLettersCode: "fur",
    locale: "fur-IT",
    androidCode: "fur-rIT",
    bcp47Code: "b+fur+IT",
    osxCode: "fur.lproj",
    osxLocale: "fur",
    dialectOf: null,
  },
  {
    id: "ff",
    name: "Fula",
    editorCode: "ff",
    twoLettersCode: "ff",
    threeLettersCode: "ful",
    locale: "ff-ZA",
    androidCode: "ff-rZA",
    bcp47Code: "b+ff+ZA",
    osxCode: "ff.lproj",
    osxLocale: "ff",
    dialectOf: null,
  },
  {
    id: "gaa",
    name: "Ga",
    editorCode: "gaa",
    twoLettersCode: "gaa",
    threeLettersCode: "gaa",
    locale: "gaa-GH",
    androidCode: "gaa-rGH",
    bcp47Code: "b+gaa+GH",
    osxCode: "gaa.lproj",
    osxLocale: "gaa",
    dialectOf: null,
  },
  {
    id: "gl",
    name: "Galician",
    editorCode: "gl",
    twoLettersCode: "gl",
    threeLettersCode: "glg",
    locale: "gl-ES",
    androidCode: "gl-rES",
    bcp47Code: "b+gl+ES",
    osxCode: "gl.lproj",
    osxLocale: "gl",
    dialectOf: null,
  },
  {
    id: "ka",
    name: "Georgian",
    editorCode: "ka",
    twoLettersCode: "ka",
    threeLettersCode: "kat",
    locale: "ka-GE",
    androidCode: "ka-rGE",
    bcp47Code: "b+ka+GE",
    osxCode: "ka.lproj",
    osxLocale: "ka",
    dialectOf: null,
  },
  {
    id: "de",
    name: "German",
    editorCode: "de",
    twoLettersCode: "de",
    threeLettersCode: "deu",
    locale: "de-DE",
    androidCode: "de-rDE",
    bcp47Code: "b+de+DE",
    osxCode: "de.lproj",
    osxLocale: "de",
    dialectOf: null,
  },
  {
    id: "de-AT",
    name: "German, Austria",
    editorCode: "deat",
    twoLettersCode: "de",
    threeLettersCode: "deu",
    locale: "de-AT",
    androidCode: "de-rAT",
    bcp47Code: "b+de+AT",
    osxCode: "de-AT.lproj",
    osxLocale: "de_AT",
    dialectOf: "de",
  },
  {
    id: "de-BE",
    name: "German, Belgium",
    editorCode: "debe",
    twoLettersCode: "de",
    threeLettersCode: "deu",
    locale: "de-BE",
    androidCode: "de-rBE",
    bcp47Code: "b+de+BE",
    osxCode: "de-BE.lproj",
    osxLocale: "de_BE",
    dialectOf: "de",
  },
  {
    id: "de-LI",
    name: "German, Liechtenstein",
    editorCode: "deli",
    twoLettersCode: "de",
    threeLettersCode: "deu",
    locale: "de-LI",
    androidCode: "de-rLI",
    bcp47Code: "b+de+LI",
    osxCode: "de-LI.lproj",
    osxLocale: "de_LI",
    dialectOf: "de",
  },
  {
    id: "de-LU",
    name: "German, Luxembourg",
    editorCode: "delu",
    twoLettersCode: "de",
    threeLettersCode: "deu",
    locale: "de-LU",
    androidCode: "de-rLU",
    bcp47Code: "b+de+LU",
    osxCode: "de-LU.lproj",
    osxLocale: "de_LU",
    dialectOf: "de",
  },
  {
    id: "de-CH",
    name: "German, Switzerland",
    editorCode: "dech",
    twoLettersCode: "de",
    threeLettersCode: "deu",
    locale: "de-CH",
    androidCode: "de-rCH",
    bcp47Code: "b+de+CH",
    osxCode: "de-CH.lproj",
    osxLocale: "de_CH",
    dialectOf: "de",
  },
  {
    id: "got",
    name: "Gothic",
    editorCode: "got",
    twoLettersCode: "got",
    threeLettersCode: "got",
    locale: "got-DE",
    androidCode: "got-rDE",
    bcp47Code: "b+got+DE",
    osxCode: "got.lproj",
    osxLocale: "got",
    dialectOf: null,
  },
  {
    id: "el",
    name: "Greek",
    editorCode: "el",
    twoLettersCode: "el",
    threeLettersCode: "ell",
    locale: "el-GR",
    androidCode: "el-rGR",
    bcp47Code: "b+el+GR",
    osxCode: "el.lproj",
    osxLocale: "el",
    dialectOf: null,
  },
  {
    id: "el-CY",
    name: "Greek, Cyprus",
    editorCode: "elcy",
    twoLettersCode: "el",
    threeLettersCode: "ell",
    locale: "el-CY",
    androidCode: "el-rCY",
    bcp47Code: "b+el+CY",
    osxCode: "el-CY.lproj",
    osxLocale: "el_CY",
    dialectOf: "el",
  },
  {
    id: "kl",
    name: "Greenlandic",
    editorCode: "kl",
    twoLettersCode: "kl",
    threeLettersCode: "kal",
    locale: "kl-GL",
    androidCode: "kl-rGL",
    bcp47Code: "b+kl+GL",
    osxCode: "kl.lproj",
    osxLocale: "kl",
    dialectOf: null,
  },
  {
    id: "gn",
    name: "Guarani",
    editorCode: "gn",
    twoLettersCode: "gn",
    threeLettersCode: "grn",
    locale: "gn-PY",
    androidCode: "gn-rPY",
    bcp47Code: "b+gn+PY",
    osxCode: "gn.lproj",
    osxLocale: "gn",
    dialectOf: null,
  },
  {
    id: "gu-IN",
    name: "Gujarati",
    editorCode: "gu",
    twoLettersCode: "gu",
    threeLettersCode: "guj",
    locale: "gu-IN",
    androidCode: "gu-rIN",
    bcp47Code: "b+gu+IN",
    osxCode: "gu.lproj",
    osxLocale: "gu",
    dialectOf: null,
  },
  {
    id: "ht",
    name: "Haitian Creole",
    editorCode: "ht",
    twoLettersCode: "ht",
    threeLettersCode: "hat",
    locale: "ht-HT",
    androidCode: "ht-rHT",
    bcp47Code: "b+ht+HT",
    osxCode: "ht.lproj",
    osxLocale: "ht",
    dialectOf: null,
  },
  {
    id: "ha",
    name: "Hausa",
    editorCode: "ha",
    twoLettersCode: "ha",
    threeLettersCode: "hau",
    locale: "ha-HG",
    androidCode: "ha-rHG",
    bcp47Code: "b+ha+HG",
    osxCode: "ha.lproj",
    osxLocale: "ha",
    dialectOf: null,
  },
  {
    id: "haw",
    name: "Hawaiian",
    editorCode: "haw",
    twoLettersCode: "haw",
    threeLettersCode: "haw",
    locale: "haw-US",
    androidCode: "haw-rUS",
    bcp47Code: "b+haw+US",
    osxCode: "haw.lproj",
    osxLocale: "haw",
    dialectOf: null,
  },
  {
    id: "he",
    name: "Hebrew",
    editorCode: "he",
    twoLettersCode: "he",
    threeLettersCode: "heb",
    locale: "he-IL",
    androidCode: "iw-rIL",
    bcp47Code: "b+he+IL",
    osxCode: "he.lproj",
    osxLocale: "he",
    dialectOf: null,
  },
  {
    id: "hz",
    name: "Herero",
    editorCode: "hz",
    twoLettersCode: "hz",
    threeLettersCode: "her",
    locale: "hz-NA",
    androidCode: "hz-rNA",
    bcp47Code: "b+hz+NA",
    osxCode: "hz.lproj",
    osxLocale: "hz",
    dialectOf: null,
  },
  {
    id: "hil",
    name: "Hiligaynon",
    editorCode: "hil",
    twoLettersCode: "hil",
    threeLettersCode: "hil",
    locale: "hil-PH",
    androidCode: "hil-rPH",
    bcp47Code: "b+hil+PH",
    osxCode: "hil.lproj",
    osxLocale: "hil",
    dialectOf: null,
  },
  {
    id: "hi",
    name: "Hindi",
    editorCode: "hi",
    twoLettersCode: "hi",
    threeLettersCode: "hin",
    locale: "hi-IN",
    androidCode: "hi-rIN",
    bcp47Code: "b+hi+IN",
    osxCode: "hi.lproj",
    osxLocale: "hi",
    dialectOf: null,
  },
  {
    id: "ho",
    name: "Hiri Motu",
    editorCode: "ho",
    twoLettersCode: "ho",
    threeLettersCode: "hmo",
    locale: "ho-PG",
    androidCode: "ho-rPG",
    bcp47Code: "b+ho+PG",
    osxCode: "ho.lproj",
    osxLocale: "ho",
    dialectOf: null,
  },
  {
    id: "hmn",
    name: "Hmong",
    editorCode: "hmn",
    twoLettersCode: "hmn",
    threeLettersCode: "hmn",
    locale: "hmn-CN",
    androidCode: "hmn-rCN",
    bcp47Code: "b+hmn+CN",
    osxCode: "hmn.lproj",
    osxLocale: "hmn",
    dialectOf: null,
  },
  {
    id: "hu",
    name: "Hungarian",
    editorCode: "hu",
    twoLettersCode: "hu",
    threeLettersCode: "hun",
    locale: "hu-HU",
    androidCode: "hu-rHU",
    bcp47Code: "b+hu+HU",
    osxCode: "hu.lproj",
    osxLocale: "hu",
    dialectOf: null,
  },
  {
    id: "is",
    name: "Icelandic",
    editorCode: "is",
    twoLettersCode: "is",
    threeLettersCode: "isl",
    locale: "is-IS",
    androidCode: "is-rIS",
    bcp47Code: "b+is+IS",
    osxCode: "is.lproj",
    osxLocale: "is",
    dialectOf: null,
  },
  {
    id: "ido",
    name: "Ido",
    editorCode: "ido",
    twoLettersCode: "io",
    threeLettersCode: "ido",
    locale: "io-EN",
    androidCode: "io-rEN",
    bcp47Code: "b+io+EN",
    osxCode: "ido.lproj",
    osxLocale: "ido",
    dialectOf: null,
  },
  {
    id: "ig",
    name: "Igbo",
    editorCode: "ig",
    twoLettersCode: "ig",
    threeLettersCode: "ibo",
    locale: "ig-NG",
    androidCode: "ig-rNG",
    bcp47Code: "b+ig+NG",
    osxCode: "ig.lproj",
    osxLocale: "ig",
    dialectOf: null,
  },
  {
    id: "ilo",
    name: "Ilokano",
    editorCode: "ilo",
    twoLettersCode: "ilo",
    threeLettersCode: "ilo",
    locale: "ilo-PH",
    androidCode: "ilo-rPH",
    bcp47Code: "b+ilo+PH",
    osxCode: "ilo.lproj",
    osxLocale: "ilo",
    dialectOf: null,
  },
  {
    id: "id",
    name: "Indonesian",
    editorCode: "id",
    twoLettersCode: "id",
    threeLettersCode: "ind",
    locale: "id-ID",
    androidCode: "in-rID",
    bcp47Code: "b+id+ID",
    osxCode: "id.lproj",
    osxLocale: "id",
    dialectOf: null,
  },
  {
    id: "iu",
    name: "Inuktitut",
    editorCode: "iu",
    twoLettersCode: "iu",
    threeLettersCode: "iku",
    locale: "iu-NU",
    androidCode: "iu-rNU",
    bcp47Code: "b+iu+NU",
    osxCode: "iu.lproj",
    osxLocale: "iu",
    dialectOf: null,
  },
  {
    id: "ga-IE",
    name: "Irish",
    editorCode: "ga",
    twoLettersCode: "ga",
    threeLettersCode: "gle",
    locale: "ga-IE",
    androidCode: "ga-rIE",
    bcp47Code: "b+ga+IE",
    osxCode: "ga.lproj",
    osxLocale: "ga",
    dialectOf: null,
  },
  {
    id: "it",
    name: "Italian",
    editorCode: "it",
    twoLettersCode: "it",
    threeLettersCode: "ita",
    locale: "it-IT",
    androidCode: "it-rIT",
    bcp47Code: "b+it+IT",
    osxCode: "it.lproj",
    osxLocale: "it",
    dialectOf: null,
  },
  {
    id: "it-CH",
    name: "Italian, Switzerland",
    editorCode: "itch",
    twoLettersCode: "it",
    threeLettersCode: "ita",
    locale: "it-CH",
    androidCode: "it-rCH",
    bcp47Code: "b+it+CH",
    osxCode: "it-CH.lproj",
    osxLocale: "it_CH",
    dialectOf: "it",
  },
  {
    id: "ja",
    name: "Japanese",
    editorCode: "ja",
    twoLettersCode: "ja",
    threeLettersCode: "jpn",
    locale: "ja-JP",
    androidCode: "ja-rJP",
    bcp47Code: "b+ja+JP",
    osxCode: "ja.lproj",
    osxLocale: "ja",
    dialectOf: null,
  },
  {
    id: "jv",
    name: "Javanese",
    editorCode: "jv",
    twoLettersCode: "jv",
    threeLettersCode: "jav",
    locale: "jv-ID",
    androidCode: "jv-rID",
    bcp47Code: "b+jv+ID",
    osxCode: "jv.lproj",
    osxLocale: "jv",
    dialectOf: null,
  },
  {
    id: "quc",
    name: "K'iche'",
    editorCode: "quc",
    twoLettersCode: "quc",
    threeLettersCode: "quc",
    locale: "quc-GT",
    androidCode: "quc-rGT",
    bcp47Code: "b+quc+GT",
    osxCode: "quc.lproj",
    osxLocale: "quc",
    dialectOf: null,
  },
  {
    id: "kab",
    name: "Kabyle",
    editorCode: "kab",
    twoLettersCode: "kab",
    threeLettersCode: "kab",
    locale: "kab-KAB",
    androidCode: "kab-rKAB",
    bcp47Code: "b+kab+KAB",
    osxCode: "kab.lproj",
    osxLocale: "kab",
    dialectOf: null,
  },
  {
    id: "kn",
    name: "Kannada",
    editorCode: "kn",
    twoLettersCode: "kn",
    threeLettersCode: "kan",
    locale: "kn-IN",
    androidCode: "kn-rIN",
    bcp47Code: "b+kn+IN",
    osxCode: "kn.lproj",
    osxLocale: "kn",
    dialectOf: null,
  },
  {
    id: "pam",
    name: "Kapampangan",
    editorCode: "pam",
    twoLettersCode: "pam",
    threeLettersCode: "pam",
    locale: "pam-PH",
    androidCode: "pam-rPH",
    bcp47Code: "b+pam+PH",
    osxCode: "pam.lproj",
    osxLocale: "pam",
    dialectOf: "fil",
  },
  {
    id: "ks",
    name: "Kashmiri",
    editorCode: "ks",
    twoLettersCode: "ks",
    threeLettersCode: "kas",
    locale: "ks-IN",
    androidCode: "ks-rIN",
    bcp47Code: "b+ks+IN",
    osxCode: "ks.lproj",
    osxLocale: "ks",
    dialectOf: null,
  },
  {
    id: "ks-PK",
    name: "Kashmiri, Pakistan",
    editorCode: "kspk",
    twoLettersCode: "ks",
    threeLettersCode: "kas",
    locale: "ks-PK",
    androidCode: "ks-rPK",
    bcp47Code: "b+ks+PK",
    osxCode: "ks-PK.lproj",
    osxLocale: "ks_PK",
    dialectOf: "ks",
  },
  {
    id: "csb",
    name: "Kashubian",
    editorCode: "csb",
    twoLettersCode: "csb",
    threeLettersCode: "csb",
    locale: "csb-PL",
    androidCode: "csb-rPL",
    bcp47Code: "b+csb+PL",
    osxCode: "csb.lproj",
    osxLocale: "csb",
    dialectOf: null,
  },
  {
    id: "kk",
    name: "Kazakh",
    editorCode: "kk",
    twoLettersCode: "kk",
    threeLettersCode: "kaz",
    locale: "kk-KZ",
    androidCode: "kk-rKZ",
    bcp47Code: "b+kk+KZ",
    osxCode: "kk.lproj",
    osxLocale: "kk",
    dialectOf: null,
  },
  {
    id: "km",
    name: "Khmer",
    editorCode: "km",
    twoLettersCode: "km",
    threeLettersCode: "khm",
    locale: "km-KH",
    androidCode: "km-rKH",
    bcp47Code: "b+km+KH",
    osxCode: "km.lproj",
    osxLocale: "km",
    dialectOf: null,
  },
  {
    id: "rw",
    name: "Kinyarwanda",
    editorCode: "rw",
    twoLettersCode: "rw",
    threeLettersCode: "kin",
    locale: "rw-RW",
    androidCode: "rw-rRW",
    bcp47Code: "b+rw+RW",
    osxCode: "rw.lproj",
    osxLocale: "rw",
    dialectOf: null,
  },
  {
    id: "tlh-AA",
    name: "Klingon",
    editorCode: "tlhaa",
    twoLettersCode: "tlh",
    threeLettersCode: "tlh",
    locale: "tlh-AA",
    androidCode: "tlh-rAA",
    bcp47Code: "b+tlh+AA",
    osxCode: "tlh.lproj",
    osxLocale: "tlh",
    dialectOf: null,
  },
  {
    id: "kv",
    name: "Komi",
    editorCode: "kv",
    twoLettersCode: "kv",
    threeLettersCode: "kom",
    locale: "kv-KO",
    androidCode: "kv-rKO",
    bcp47Code: "b+kv+KO",
    osxCode: "kv.lproj",
    osxLocale: "kv",
    dialectOf: null,
  },
  {
    id: "kg",
    name: "Kongo",
    editorCode: "kg",
    twoLettersCode: "kg",
    threeLettersCode: "kon",
    locale: "kg-CG",
    androidCode: "kg-rCG",
    bcp47Code: "b+kg+CG",
    osxCode: "kg.lproj",
    osxLocale: "kg",
    dialectOf: null,
  },
  {
    id: "kok",
    name: "Konkani",
    editorCode: "kok",
    twoLettersCode: "kok",
    threeLettersCode: "kok",
    locale: "kok-IN",
    androidCode: "kok-rIN",
    bcp47Code: "b+kok+IN",
    osxCode: "kok.lproj",
    osxLocale: "kok",
    dialectOf: null,
  },
  {
    id: "ko",
    name: "Korean",
    editorCode: "ko",
    twoLettersCode: "ko",
    threeLettersCode: "kor",
    locale: "ko-KR",
    androidCode: "ko-rKR",
    bcp47Code: "b+ko+KR",
    osxCode: "ko.lproj",
    osxLocale: "ko",
    dialectOf: null,
  },
  {
    id: "ku",
    name: "Kurdish",
    editorCode: "ku",
    twoLettersCode: "ku",
    threeLettersCode: "kur",
    locale: "ku-TR",
    androidCode: "ku-rTR",
    bcp47Code: "b+ku+TR",
    osxCode: "ku.lproj",
    osxLocale: "ku",
    dialectOf: null,
  },
  {
    id: "kmr",
    name: "Kurmanji (Kurdish)",
    editorCode: "kmr",
    twoLettersCode: "ku",
    threeLettersCode: "kmr",
    locale: "kmr-TR",
    androidCode: "kmr-rTR",
    bcp47Code: "b+kmr+TR",
    osxCode: "kmr.lproj",
    osxLocale: "kmr",
    dialectOf: "ku",
  },
  {
    id: "kj",
    name: "Kwanyama",
    editorCode: "kj",
    twoLettersCode: "kj",
    threeLettersCode: "kua",
    locale: "kj-AO",
    androidCode: "kj-rAO",
    bcp47Code: "b+kj+AO",
    osxCode: "kj.lproj",
    osxLocale: "kj",
    dialectOf: null,
  },
  {
    id: "ky",
    name: "Kyrgyz",
    editorCode: "ky",
    twoLettersCode: "ky",
    threeLettersCode: "kir",
    locale: "ky-KG",
    androidCode: "ky-rKG",
    bcp47Code: "b+ky+KG",
    osxCode: "ky.lproj",
    osxLocale: "ky",
    dialectOf: null,
  },
  {
    id: "lol",
    name: "LOLCAT",
    editorCode: "lol",
    twoLettersCode: "lol",
    threeLettersCode: "lol",
    locale: "lol-US",
    androidCode: "lol-rUS",
    bcp47Code: "b+lol+US",
    osxCode: "lol.lproj",
    osxLocale: "lol",
    dialectOf: null,
  },
  {
    id: "lo",
    name: "Lao",
    editorCode: "lo",
    twoLettersCode: "lo",
    threeLettersCode: "lao",
    locale: "lo-LA",
    androidCode: "lo-rLA",
    bcp47Code: "b+lo+LA",
    osxCode: "lo.lproj",
    osxLocale: "lo",
    dialectOf: null,
  },
  {
    id: "la-LA",
    name: "Latin",
    editorCode: "lala",
    twoLettersCode: "la",
    threeLettersCode: "lat",
    locale: "la-LA",
    androidCode: "la-rLA",
    bcp47Code: "b+la+LA",
    osxCode: "la.lproj",
    osxLocale: "la",
    dialectOf: null,
  },
  {
    id: "lv",
    name: "Latvian",
    editorCode: "lv",
    twoLettersCode: "lv",
    threeLettersCode: "lav",
    locale: "lv-LV",
    androidCode: "lv-rLV",
    bcp47Code: "b+lv+LV",
    osxCode: "lv.lproj",
    osxLocale: "lv",
    dialectOf: null,
  },
  {
    id: "lij",
    name: "Ligurian",
    editorCode: "lij",
    twoLettersCode: "lij",
    threeLettersCode: "lij",
    locale: "lij-IT",
    androidCode: "lij-rIT",
    bcp47Code: "b+lij+IT",
    osxCode: "lij.lproj",
    osxLocale: "lij",
    dialectOf: null,
  },
  {
    id: "li",
    name: "Limburgish",
    editorCode: "li",
    twoLettersCode: "li",
    threeLettersCode: "lim",
    locale: "li-LI",
    androidCode: "li-rLI",
    bcp47Code: "b+li+LI",
    osxCode: "li.lproj",
    osxLocale: "li",
    dialectOf: null,
  },
  {
    id: "ln",
    name: "Lingala",
    editorCode: "ln",
    twoLettersCode: "ln",
    threeLettersCode: "lin",
    locale: "ln-CD",
    androidCode: "ln-rCD",
    bcp47Code: "b+ln+CD",
    osxCode: "ln.lproj",
    osxLocale: "ln",
    dialectOf: null,
  },
  {
    id: "lt",
    name: "Lithuanian",
    editorCode: "lt",
    twoLettersCode: "lt",
    threeLettersCode: "lit",
    locale: "lt-LT",
    androidCode: "lt-rLT",
    bcp47Code: "b+lt+LT",
    osxCode: "lt.lproj",
    osxLocale: "lt",
    dialectOf: null,
  },
  {
    id: "jbo",
    name: "Lojban",
    editorCode: "jbo",
    twoLettersCode: "jbo",
    threeLettersCode: "jbo",
    locale: "jbo-EN",
    androidCode: "jbo-rEN",
    bcp47Code: "b+jbo+EN",
    osxCode: "jbo.lproj",
    osxLocale: "jbo",
    dialectOf: null,
  },
  {
    id: "nds",
    name: "Low German",
    editorCode: "nds",
    twoLettersCode: "nds",
    threeLettersCode: "nds",
    locale: "nds-DE",
    androidCode: "nds-rDE",
    bcp47Code: "b+nds+DE",
    osxCode: "nds.lproj",
    osxLocale: "nds",
    dialectOf: null,
  },
  {
    id: "dsb-DE",
    name: "Lower Sorbian",
    editorCode: "dsbde",
    twoLettersCode: "dsb",
    threeLettersCode: "dsb",
    locale: "dsb-DE",
    androidCode: "dsb-rDE",
    bcp47Code: "b+dsb+DE",
    osxCode: "dsb.lproj",
    osxLocale: "dsb",
    dialectOf: null,
  },
  {
    id: "lg",
    name: "Luganda",
    editorCode: "lg",
    twoLettersCode: "lg",
    threeLettersCode: "lug",
    locale: "lg-UG",
    androidCode: "lg-rUG",
    bcp47Code: "b+lg+UG",
    osxCode: "lg.lproj",
    osxLocale: "lg",
    dialectOf: null,
  },
  {
    id: "luy",
    name: "Luhya",
    editorCode: "luy",
    twoLettersCode: "luy",
    threeLettersCode: "luy",
    locale: "luy-KE",
    androidCode: "luy-rKE",
    bcp47Code: "b+luy+KE",
    osxCode: "luy.lproj",
    osxLocale: "luy",
    dialectOf: null,
  },
  {
    id: "lb",
    name: "Luxembourgish",
    editorCode: "lb",
    twoLettersCode: "lb",
    threeLettersCode: "ltz",
    locale: "lb-LU",
    androidCode: "lb-rLU",
    bcp47Code: "b+lb+LU",
    osxCode: "lb.lproj",
    osxLocale: "lb",
    dialectOf: null,
  },
  {
    id: "mk",
    name: "Macedonian",
    editorCode: "mk",
    twoLettersCode: "mk",
    threeLettersCode: "mkd",
    locale: "mk-MK",
    androidCode: "mk-rMK",
    bcp47Code: "b+mk+MK",
    osxCode: "mk.lproj",
    osxLocale: "mk",
    dialectOf: null,
  },
  {
    id: "mai",
    name: "Maithili",
    editorCode: "mai",
    twoLettersCode: "mai",
    threeLettersCode: "mai",
    locale: "mai-IN",
    androidCode: "mai-rIN",
    bcp47Code: "b+mai+IN",
    osxCode: "mai.lproj",
    osxLocale: "mai",
    dialectOf: null,
  },
  {
    id: "mg",
    name: "Malagasy",
    editorCode: "mg",
    twoLettersCode: "mg",
    threeLettersCode: "mlg",
    locale: "mg-MG",
    androidCode: "mg-rMG",
    bcp47Code: "b+mg+MG",
    osxCode: "mg.lproj",
    osxLocale: "mg",
    dialectOf: null,
  },
  {
    id: "ms",
    name: "Malay",
    editorCode: "ms",
    twoLettersCode: "ms",
    threeLettersCode: "msa",
    locale: "ms-MY",
    androidCode: "ms-rMY",
    bcp47Code: "b+ms+MY",
    osxCode: "ms.lproj",
    osxLocale: "ms",
    dialectOf: null,
  },
  {
    id: "ms-BN",
    name: "Malay, Brunei",
    editorCode: "msbn",
    twoLettersCode: "ms",
    threeLettersCode: "msa",
    locale: "ms-BN",
    androidCode: "ms-rBN",
    bcp47Code: "b+ms+BN",
    osxCode: "ms-BN.lproj",
    osxLocale: "ms_BN",
    dialectOf: "ms",
  },
  {
    id: "ml-IN",
    name: "Malayalam",
    editorCode: "mlin",
    twoLettersCode: "ml",
    threeLettersCode: "mal",
    locale: "ml-IN",
    androidCode: "ml-rIN",
    bcp47Code: "b+ml+IN",
    osxCode: "ml.lproj",
    osxLocale: "ml",
    dialectOf: null,
  },
  {
    id: "mt",
    name: "Maltese",
    editorCode: "mt",
    twoLettersCode: "mt",
    threeLettersCode: "mlt",
    locale: "mt-MT",
    androidCode: "mt-rMT",
    bcp47Code: "b+mt+MT",
    osxCode: "mt.lproj",
    osxLocale: "mt",
    dialectOf: null,
  },
  {
    id: "gv",
    name: "Manx",
    editorCode: "gv",
    twoLettersCode: "gv",
    threeLettersCode: "glv",
    locale: "gv-IM",
    androidCode: "gv-rIM",
    bcp47Code: "b+gv+IM",
    osxCode: "gv.lproj",
    osxLocale: "gv",
    dialectOf: null,
  },
  {
    id: "mi",
    name: "Maori",
    editorCode: "mi",
    twoLettersCode: "mi",
    threeLettersCode: "mri",
    locale: "mi-NZ",
    androidCode: "mi-rNZ",
    bcp47Code: "b+mi+NZ",
    osxCode: "mi.lproj",
    osxLocale: "mi",
    dialectOf: null,
  },
  {
    id: "arn",
    name: "Mapudungun",
    editorCode: "arn",
    twoLettersCode: "arn",
    threeLettersCode: "arn",
    locale: "arn-CL",
    androidCode: "arn-rCL",
    bcp47Code: "b+arn+CL",
    osxCode: "arn.lproj",
    osxLocale: "arn",
    dialectOf: null,
  },
  {
    id: "mr",
    name: "Marathi",
    editorCode: "mr",
    twoLettersCode: "mr",
    threeLettersCode: "mar",
    locale: "mr-IN",
    androidCode: "mr-rIN",
    bcp47Code: "b+mr+IN",
    osxCode: "mr.lproj",
    osxLocale: "mr",
    dialectOf: null,
  },
  {
    id: "mh",
    name: "Marshallese",
    editorCode: "mh",
    twoLettersCode: "mh",
    threeLettersCode: "mah",
    locale: "mh-MH",
    androidCode: "mh-rMH",
    bcp47Code: "b+mh+MH",
    osxCode: "mh.lproj",
    osxLocale: "mh",
    dialectOf: null,
  },
  {
    id: "moh",
    name: "Mohawk",
    editorCode: "moh",
    twoLettersCode: "moh",
    threeLettersCode: "moh",
    locale: "moh-CA",
    androidCode: "moh-rCA",
    bcp47Code: "b+moh+CA",
    osxCode: "moh.lproj",
    osxLocale: "moh",
    dialectOf: null,
  },
  {
    id: "mn",
    name: "Mongolian",
    editorCode: "mn",
    twoLettersCode: "mn",
    threeLettersCode: "mon",
    locale: "mn-MN",
    androidCode: "mn-rMN",
    bcp47Code: "b+mn+MN",
    osxCode: "mn.lproj",
    osxLocale: "mn",
    dialectOf: null,
  },
  {
    id: "sr-Cyrl-ME",
    name: "Montenegrin (Cyrillic)",
    editorCode: "srcyrlme",
    twoLettersCode: "sr",
    threeLettersCode: "srp",
    locale: "sr-Cyrl-ME",
    androidCode: "sr-rCyrl-rME",
    bcp47Code: "b+sr+Cyrl+ME",
    osxCode: "sr-Cyrl-ME.lproj",
    osxLocale: "sr_Cyrl_ME",
    dialectOf: null,
  },
  {
    id: "me",
    name: "Montenegrin (Latin)",
    editorCode: "me",
    twoLettersCode: "me",
    threeLettersCode: "srp",
    locale: "me-ME",
    androidCode: "me-rME",
    bcp47Code: "b+me+ME",
    osxCode: "me.lproj",
    osxLocale: "me",
    dialectOf: null,
  },
  {
    id: "mos",
    name: "Mossi",
    editorCode: "mos",
    twoLettersCode: "mos",
    threeLettersCode: "mos",
    locale: "mos-MOS",
    androidCode: "mos-rMOS",
    bcp47Code: "b+mos+MOS",
    osxCode: "mos.lproj",
    osxLocale: "mos",
    dialectOf: null,
  },
  {
    id: "na",
    name: "Nauru",
    editorCode: "na",
    twoLettersCode: "na",
    threeLettersCode: "nau",
    locale: "na-NR",
    androidCode: "na-rNR",
    bcp47Code: "b+na+NR",
    osxCode: "na.lproj",
    osxLocale: "na",
    dialectOf: null,
  },
  {
    id: "ng",
    name: "Ndonga",
    editorCode: "ng",
    twoLettersCode: "ng",
    threeLettersCode: "ndo",
    locale: "ng-NA",
    androidCode: "ng-rNA",
    bcp47Code: "b+ng+NA",
    osxCode: "ng.lproj",
    osxLocale: "ng",
    dialectOf: null,
  },
  {
    id: "ne-NP",
    name: "Nepali",
    editorCode: "nenp",
    twoLettersCode: "ne",
    threeLettersCode: "nep",
    locale: "ne-NP",
    androidCode: "ne-rNP",
    bcp47Code: "b+ne+NP",
    osxCode: "ne.lproj",
    osxLocale: "ne",
    dialectOf: null,
  },
  {
    id: "ne-IN",
    name: "Nepali, India",
    editorCode: "nein",
    twoLettersCode: "ne",
    threeLettersCode: "nep",
    locale: "ne-IN",
    androidCode: "ne-rIN",
    bcp47Code: "b+ne+IN",
    osxCode: "ne-IN.lproj",
    osxLocale: "ne_IN",
    dialectOf: null,
  },
  {
    id: "pcm",
    name: "Nigerian Pidgin",
    editorCode: "pcm",
    twoLettersCode: "pcm",
    threeLettersCode: "pcm",
    locale: "pcm-NG",
    androidCode: "pcm-rNG",
    bcp47Code: "b+pcm+NG",
    osxCode: "pcm.lproj",
    osxLocale: "pcm",
    dialectOf: null,
  },
  {
    id: "se",
    name: "Northern Sami",
    editorCode: "se",
    twoLettersCode: "se",
    threeLettersCode: "sme",
    locale: "se-NO",
    androidCode: "se-rNO",
    bcp47Code: "b+se+NO",
    osxCode: "se.lproj",
    osxLocale: "se",
    dialectOf: null,
  },
  {
    id: "nso",
    name: "Northern Sotho",
    editorCode: "nso",
    twoLettersCode: "nso",
    threeLettersCode: "nso",
    locale: "ns-ZA",
    androidCode: "ns-rZA",
    bcp47Code: "b+ns+ZA",
    osxCode: "nso.lproj",
    osxLocale: "nso",
    dialectOf: null,
  },
  {
    id: "no",
    name: "Norwegian",
    editorCode: "no",
    twoLettersCode: "no",
    threeLettersCode: "nor",
    locale: "no-NO",
    androidCode: "no-rNO",
    bcp47Code: "b+no+NO",
    osxCode: "no.lproj",
    osxLocale: "no",
    dialectOf: null,
  },
  {
    id: "nb",
    name: "Norwegian Bokmal",
    editorCode: "nb",
    twoLettersCode: "nb",
    threeLettersCode: "nob",
    locale: "nb-NO",
    androidCode: "nb-rNO",
    bcp47Code: "b+nb+NO",
    osxCode: "nb.lproj",
    osxLocale: "nb",
    dialectOf: "no",
  },
  {
    id: "nn-NO",
    name: "Norwegian Nynorsk",
    editorCode: "nnno",
    twoLettersCode: "nn",
    threeLettersCode: "nno",
    locale: "nn-NO",
    androidCode: "nn-rNO",
    bcp47Code: "b+nn+NO",
    osxCode: "nn-NO.lproj",
    osxLocale: "nn_NO",
    dialectOf: "no",
  },
  {
    id: "oc",
    name: "Occitan",
    editorCode: "oc",
    twoLettersCode: "oc",
    threeLettersCode: "oci",
    locale: "oc-FR",
    androidCode: "oc-rFR",
    bcp47Code: "b+oc+FR",
    osxCode: "oc.lproj",
    osxLocale: "oc",
    dialectOf: null,
  },
  {
    id: "or",
    name: "Odia",
    editorCode: "or",
    twoLettersCode: "or",
    threeLettersCode: "ori",
    locale: "or-IN",
    androidCode: "or-rIN",
    bcp47Code: "b+or+IN",
    osxCode: "or.lproj",
    osxLocale: "or",
    dialectOf: null,
  },
  {
    id: "oj",
    name: "Ojibwe",
    editorCode: "oj",
    twoLettersCode: "oj",
    threeLettersCode: "oji",
    locale: "oj-CA",
    androidCode: "oj-rCA",
    bcp47Code: "b+oj+CA",
    osxCode: "oj.lproj",
    osxLocale: "oj",
    dialectOf: null,
  },
  {
    id: "om",
    name: "Oromo",
    editorCode: "om",
    twoLettersCode: "om",
    threeLettersCode: "orm",
    locale: "om-ET",
    androidCode: "om-rET",
    bcp47Code: "b+om+ET",
    osxCode: "om.lproj",
    osxLocale: "om",
    dialectOf: null,
  },
  {
    id: "os",
    name: "Ossetian",
    editorCode: "os",
    twoLettersCode: "os",
    threeLettersCode: "oss",
    locale: "os-SE",
    androidCode: "os-rSE",
    bcp47Code: "b+os+SE",
    osxCode: "os.lproj",
    osxLocale: "os",
    dialectOf: null,
  },
  {
    id: "pi",
    name: "Pali",
    editorCode: "pi",
    twoLettersCode: "pi",
    threeLettersCode: "pli",
    locale: "pi-IN",
    androidCode: "pi-rIN",
    bcp47Code: "b+pi+IN",
    osxCode: "pi.lproj",
    osxLocale: "pi",
    dialectOf: null,
  },
  {
    id: "pap",
    name: "Papiamento",
    editorCode: "pap",
    twoLettersCode: "pap",
    threeLettersCode: "pap",
    locale: "pap-PAP",
    androidCode: "pap-rPAP",
    bcp47Code: "b+pap+PAP",
    osxCode: "pap.lproj",
    osxLocale: "pap",
    dialectOf: null,
  },
  {
    id: "ps",
    name: "Pashto",
    editorCode: "ps",
    twoLettersCode: "ps",
    threeLettersCode: "pus",
    locale: "ps-AF",
    androidCode: "ps-rAF",
    bcp47Code: "b+ps+AF",
    osxCode: "ps.lproj",
    osxLocale: "ps",
    dialectOf: null,
  },
  {
    id: "fa",
    name: "Persian",
    editorCode: "fa",
    twoLettersCode: "fa",
    threeLettersCode: "fas",
    locale: "fa-IR",
    androidCode: "fa-rIR",
    bcp47Code: "b+fa+IR",
    osxCode: "fa.lproj",
    osxLocale: "fa",
    dialectOf: null,
  },
  {
    id: "en-PT",
    name: "Pirate English",
    editorCode: "enpt",
    twoLettersCode: "en",
    threeLettersCode: "eng",
    locale: "en-PT",
    androidCode: "en-rPT",
    bcp47Code: "b+en+PT",
    osxCode: "en-PT.lproj",
    osxLocale: "en_PT",
    dialectOf: null,
  },
  {
    id: "pl",
    name: "Polish",
    editorCode: "pl",
    twoLettersCode: "pl",
    threeLettersCode: "pol",
    locale: "pl-PL",
    androidCode: "pl-rPL",
    bcp47Code: "b+pl+PL",
    osxCode: "pl.lproj",
    osxLocale: "pl",
    dialectOf: null,
  },
  {
    id: "pt-PT",
    name: "Portuguese",
    editorCode: "pt",
    twoLettersCode: "pt",
    threeLettersCode: "por",
    locale: "pt-PT",
    androidCode: "pt-rPT",
    bcp47Code: "b+pt+PT",
    osxCode: "pt.lproj",
    osxLocale: "pt",
    dialectOf: null,
  },
  {
    id: "pt-BR",
    name: "Portuguese, Brazilian",
    editorCode: "ptbr",
    twoLettersCode: "pt",
    threeLettersCode: "por",
    locale: "pt-BR",
    androidCode: "pt-rBR",
    bcp47Code: "b+pt+BR",
    osxCode: "pt-BR.lproj",
    osxLocale: "pt_BR",
    dialectOf: null,
  },
  {
    id: "pa-IN",
    name: "Punjabi",
    editorCode: "pain",
    twoLettersCode: "pa",
    threeLettersCode: "pan",
    locale: "pa-IN",
    androidCode: "pa-rIN",
    bcp47Code: "b+pa+IN",
    osxCode: "pa.lproj",
    osxLocale: "pa",
    dialectOf: null,
  },
  {
    id: "pa-PK",
    name: "Punjabi, Pakistan",
    editorCode: "papk",
    twoLettersCode: "pa",
    threeLettersCode: "pan",
    locale: "pa-PK",
    androidCode: "pa-rPK",
    bcp47Code: "b+pa+PK",
    osxCode: "pa-PK.lproj",
    osxLocale: "pa_PK",
    dialectOf: "pa-IN",
  },
  {
    id: "qu",
    name: "Quechua",
    editorCode: "qu",
    twoLettersCode: "qu",
    threeLettersCode: "que",
    locale: "qu-PE",
    androidCode: "qu-rPE",
    bcp47Code: "b+qu+PE",
    osxCode: "qu.lproj",
    osxLocale: "qu",
    dialectOf: null,
  },
  {
    id: "qya-AA",
    name: "Quenya",
    editorCode: "qyaaa",
    twoLettersCode: "qya",
    threeLettersCode: "qya",
    locale: "qya-AA",
    androidCode: "qya-rAA",
    bcp47Code: "b+qya+AA",
    osxCode: "qya.lproj",
    osxLocale: "qya",
    dialectOf: null,
  },
  {
    id: "ro",
    name: "Romanian",
    editorCode: "ro",
    twoLettersCode: "ro",
    threeLettersCode: "ron",
    locale: "ro-RO",
    androidCode: "ro-rRO",
    bcp47Code: "b+ro+RO",
    osxCode: "ro.lproj",
    osxLocale: "ro",
    dialectOf: null,
  },
  {
    id: "rm-CH",
    name: "Romansh",
    editorCode: "rmch",
    twoLettersCode: "rm",
    threeLettersCode: "roh",
    locale: "rm-CH",
    androidCode: "rm-rCH",
    bcp47Code: "b+rm+CH",
    osxCode: "rm.lproj",
    osxLocale: "rm",
    dialectOf: null,
  },
  {
    id: "rn",
    name: "Rundi",
    editorCode: "rn",
    twoLettersCode: "rn",
    threeLettersCode: "run",
    locale: "rn-BI",
    androidCode: "rn-rBI",
    bcp47Code: "b+rn+BI",
    osxCode: "rn.lproj",
    osxLocale: "rn",
    dialectOf: null,
  },
  {
    id: "ru",
    name: "Russian",
    editorCode: "ru",
    twoLettersCode: "ru",
    threeLettersCode: "rus",
    locale: "ru-RU",
    androidCode: "ru-rRU",
    bcp47Code: "b+ru+RU",
    osxCode: "ru.lproj",
    osxLocale: "ru",
    dialectOf: null,
  },
  {
    id: "ru-BY",
    name: "Russian, Belarus",
    editorCode: "ruby",
    twoLettersCode: "ru",
    threeLettersCode: "rus",
    locale: "ru-BY",
    androidCode: "ru-rBY",
    bcp47Code: "b+ru+BY",
    osxCode: "ru-BY.lproj",
    osxLocale: "ru_BY",
    dialectOf: "ru",
  },
  {
    id: "ru-MD",
    name: "Russian, Moldova",
    editorCode: "rumd",
    twoLettersCode: "ru",
    threeLettersCode: "rus",
    locale: "ru-MD",
    androidCode: "ru-rMD",
    bcp47Code: "b+ru+MD",
    osxCode: "ru-MD.lproj",
    osxLocale: "ru_MD",
    dialectOf: "ru",
  },
  {
    id: "ry-UA",
    name: "Rusyn",
    editorCode: "ryua",
    twoLettersCode: "ry",
    threeLettersCode: "sla",
    locale: "ry-UA",
    androidCode: "ry-rUA",
    bcp47Code: "b+ry+UA",
    osxCode: "ry.lproj",
    osxLocale: "ry",
    dialectOf: null,
  },
  {
    id: "ru-UA",
    name: "Rսssian, Սkraine",
    editorCode: "ruua",
    twoLettersCode: "ru",
    threeLettersCode: "rus",
    locale: "ru-UA",
    androidCode: "ru-rUA",
    bcp47Code: "b+ru+UA",
    osxCode: "ru-UA.lproj",
    osxLocale: "ru_UA",
    dialectOf: "ru",
  },
  {
    id: "sah",
    name: "Sakha",
    editorCode: "sah",
    twoLettersCode: "sah",
    threeLettersCode: "sah",
    locale: "sah-SAH",
    androidCode: "sah-rSAH",
    bcp47Code: "b+sah+SAH",
    osxCode: "sah.lproj",
    osxLocale: "sah",
    dialectOf: null,
  },
  {
    id: "sg",
    name: "Sango",
    editorCode: "sg",
    twoLettersCode: "sg",
    threeLettersCode: "sag",
    locale: "sg-CF",
    androidCode: "sg-rCF",
    bcp47Code: "b+sg+CF",
    osxCode: "sg.lproj",
    osxLocale: "sg",
    dialectOf: null,
  },
  {
    id: "sa",
    name: "Sanskrit",
    editorCode: "sa",
    twoLettersCode: "sa",
    threeLettersCode: "san",
    locale: "sa-IN",
    androidCode: "sa-rIN",
    bcp47Code: "b+sa+IN",
    osxCode: "sa.lproj",
    osxLocale: "sa",
    dialectOf: null,
  },
  {
    id: "sat",
    name: "Santali",
    editorCode: "sat",
    twoLettersCode: "sat",
    threeLettersCode: "sat",
    locale: "sat-IN",
    androidCode: "sat-rIN",
    bcp47Code: "b+sat+IN",
    osxCode: "sat.lproj",
    osxLocale: "sat",
    dialectOf: null,
  },
  {
    id: "sc",
    name: "Sardinian",
    editorCode: "sc",
    twoLettersCode: "sc",
    threeLettersCode: "srd",
    locale: "sc-IT",
    androidCode: "sc-rIT",
    bcp47Code: "b+sc+IT",
    osxCode: "sc.lproj",
    osxLocale: "sc",
    dialectOf: null,
  },
  {
    id: "sco",
    name: "Scots",
    editorCode: "sco",
    twoLettersCode: "sco",
    threeLettersCode: "sco",
    locale: "sco-GB",
    androidCode: "sco-rGB",
    bcp47Code: "b+sco+GB",
    osxCode: "sco.lproj",
    osxLocale: "sco",
    dialectOf: null,
  },
  {
    id: "gd",
    name: "Scottish Gaelic",
    editorCode: "gd",
    twoLettersCode: "gd",
    threeLettersCode: "gla",
    locale: "gd-GB",
    androidCode: "gd-rGB",
    bcp47Code: "b+gd+GB",
    osxCode: "gd.lproj",
    osxLocale: "gd",
    dialectOf: null,
  },
  {
    id: "sr",
    name: "Serbian (Cyrillic)",
    editorCode: "sr",
    twoLettersCode: "sr",
    threeLettersCode: "srp",
    locale: "sr-SP",
    androidCode: "sr-rSP",
    bcp47Code: "b+sr+Cyrl",
    osxCode: "sr.lproj",
    osxLocale: "sr",
    dialectOf: null,
  },
  {
    id: "sr-CS",
    name: "Serbian (Latin)",
    editorCode: "srcs",
    twoLettersCode: "sr",
    threeLettersCode: "srp",
    locale: "sr-CS",
    androidCode: "sr-rCS",
    bcp47Code: "b+sr+Latn",
    osxCode: "sr-Latn.lproj",
    osxLocale: "sr_Latn",
    dialectOf: null,
  },
  {
    id: "sh",
    name: "Serbo-Croatian",
    editorCode: "sh",
    twoLettersCode: "sh",
    threeLettersCode: "hbs",
    locale: "sh-HR",
    androidCode: "sh-rHR",
    bcp47Code: "b+sh+HR",
    osxCode: "sh.lproj",
    osxLocale: "sh",
    dialectOf: null,
  },
  {
    id: "crs",
    name: "Seychellois Creole",
    editorCode: "crs",
    twoLettersCode: "crs",
    threeLettersCode: "crs",
    locale: "crs-SC",
    androidCode: "crs-rSC",
    bcp47Code: "b+crs+SC",
    osxCode: "crs.lproj",
    osxLocale: "crs",
    dialectOf: null,
  },
  {
    id: "sn",
    name: "Shona",
    editorCode: "sn",
    twoLettersCode: "sn",
    threeLettersCode: "sna",
    locale: "sn-ZW",
    androidCode: "sn-rZW",
    bcp47Code: "b+sn+ZW",
    osxCode: "sn.lproj",
    osxLocale: "sn",
    dialectOf: null,
  },
  {
    id: "ii",
    name: "Sichuan Yi",
    editorCode: "ii",
    twoLettersCode: "ii",
    threeLettersCode: "iii",
    locale: "ii-CN",
    androidCode: "ii-rCN",
    bcp47Code: "b+ii+CN",
    osxCode: "ii.lproj",
    osxLocale: "ii",
    dialectOf: null,
  },
  {
    id: "sd",
    name: "Sindhi",
    editorCode: "sd",
    twoLettersCode: "sd",
    threeLettersCode: "snd",
    locale: "sd-PK",
    androidCode: "sd-rPK",
    bcp47Code: "b+sd+PK",
    osxCode: "sd.lproj",
    osxLocale: "sd",
    dialectOf: null,
  },
  {
    id: "si-LK",
    name: "Sinhala",
    editorCode: "silk",
    twoLettersCode: "si",
    threeLettersCode: "sin",
    locale: "si-LK",
    androidCode: "si-rLK",
    bcp47Code: "b+si+LK",
    osxCode: "si.lproj",
    osxLocale: "si",
    dialectOf: null,
  },
  {
    id: "sk",
    name: "Slovak",
    editorCode: "sk",
    twoLettersCode: "sk",
    threeLettersCode: "slk",
    locale: "sk-SK",
    androidCode: "sk-rSK",
    bcp47Code: "b+sk+SK",
    osxCode: "sk.lproj",
    osxLocale: "sk",
    dialectOf: null,
  },
  {
    id: "sl",
    name: "Slovenian",
    editorCode: "sl",
    twoLettersCode: "sl",
    threeLettersCode: "slv",
    locale: "sl-SI",
    androidCode: "sl-rSI",
    bcp47Code: "b+sl+SI",
    osxCode: "sl.lproj",
    osxLocale: "sl",
    dialectOf: null,
  },
  {
    id: "so",
    name: "Somali",
    editorCode: "so",
    twoLettersCode: "so",
    threeLettersCode: "som",
    locale: "so-SO",
    androidCode: "so-rSO",
    bcp47Code: "b+so+SO",
    osxCode: "so.lproj",
    osxLocale: "so",
    dialectOf: null,
  },
  {
    id: "son",
    name: "Songhay",
    editorCode: "son",
    twoLettersCode: "son",
    threeLettersCode: "son",
    locale: "son-ZA",
    androidCode: "son-rZA",
    bcp47Code: "b+son+ZA",
    osxCode: "son.lproj",
    osxLocale: "son",
    dialectOf: null,
  },
  {
    id: "ckb",
    name: "Sorani (Kurdish)",
    editorCode: "ckb",
    twoLettersCode: "ku",
    threeLettersCode: "ckb",
    locale: "ckb-IR",
    androidCode: "ckb-rIR",
    bcp47Code: "b+ckb+IR",
    osxCode: "ckb.lproj",
    osxLocale: "ckb",
    dialectOf: "ku",
  },
  {
    id: "nr",
    name: "Southern Ndebele",
    editorCode: "nr",
    twoLettersCode: "nr",
    threeLettersCode: "nbl",
    locale: "nr-ZA",
    androidCode: "nr-rZA",
    bcp47Code: "b+nr+ZA",
    osxCode: "nr.lproj",
    osxLocale: "nr",
    dialectOf: null,
  },
  {
    id: "sma",
    name: "Southern Sami",
    editorCode: "sma",
    twoLettersCode: "sma",
    threeLettersCode: "sma",
    locale: "sma-NO",
    androidCode: "sma-rNO",
    bcp47Code: "b+sma+NO",
    osxCode: "sma.lproj",
    osxLocale: "sma",
    dialectOf: null,
  },
  {
    id: "st",
    name: "Southern Sotho",
    editorCode: "st",
    twoLettersCode: "st",
    threeLettersCode: "sot",
    locale: "st-ZA",
    androidCode: "st-rZA",
    bcp47Code: "b+st+ZA",
    osxCode: "st.lproj",
    osxLocale: "st",
    dialectOf: null,
  },
  {
    id: "es-ES",
    name: "Spanish",
    editorCode: "es",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-ES",
    androidCode: "es-rES",
    bcp47Code: "b+es+ES",
    osxCode: "es.lproj",
    osxLocale: "es",
    dialectOf: null,
  },
  {
    id: "es-EM",
    name: "Spanish (Modern)",
    editorCode: "esem",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-EM",
    androidCode: "es-rEM",
    bcp47Code: "b+es+EM",
    osxCode: "es-EM.lproj",
    osxLocale: "es_EM",
    dialectOf: "es-ES",
  },
  {
    id: "es-AR",
    name: "Spanish, Argentina",
    editorCode: "esar",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-AR",
    androidCode: "es-rAR",
    bcp47Code: "b+es+AR",
    osxCode: "es-AR.lproj",
    osxLocale: "es_AR",
    dialectOf: "es-ES",
  },
  {
    id: "es-BO",
    name: "Spanish, Bolivia",
    editorCode: "esbo",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-BO",
    androidCode: "es-rBO",
    bcp47Code: "b+es+BO",
    osxCode: "es-BO.lproj",
    osxLocale: "es_BO",
    dialectOf: "es-ES",
  },
  {
    id: "es-CL",
    name: "Spanish, Chile",
    editorCode: "escl",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-CL",
    androidCode: "es-rCL",
    bcp47Code: "b+es+CL",
    osxCode: "es-CL.lproj",
    osxLocale: "es_CL",
    dialectOf: "es-ES",
  },
  {
    id: "es-CO",
    name: "Spanish, Colombia",
    editorCode: "esco",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-CO",
    androidCode: "es-rCO",
    bcp47Code: "b+es+CO",
    osxCode: "es-CO.lproj",
    osxLocale: "es_CO",
    dialectOf: "es-ES",
  },
  {
    id: "es-CR",
    name: "Spanish, Costa Rica",
    editorCode: "escr",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-CR",
    androidCode: "es-rCR",
    bcp47Code: "b+es+CR",
    osxCode: "es-CR.lproj",
    osxLocale: "es_CR",
    dialectOf: "es-ES",
  },
  {
    id: "es-DO",
    name: "Spanish, Dominican Republic",
    editorCode: "esdo",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-DO",
    androidCode: "es-rDO",
    bcp47Code: "b+es+DO",
    osxCode: "es-DO.lproj",
    osxLocale: "es_DO",
    dialectOf: "es-ES",
  },
  {
    id: "es-EC",
    name: "Spanish, Ecuador",
    editorCode: "esec",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-EC",
    androidCode: "es-rEC",
    bcp47Code: "b+es+EC",
    osxCode: "es-EC.lproj",
    osxLocale: "es_EC",
    dialectOf: "es-ES",
  },
  {
    id: "es-SV",
    name: "Spanish, El Salvador",
    editorCode: "essv",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-SV",
    androidCode: "es-rSV",
    bcp47Code: "b+es+SV",
    osxCode: "es-SV.lproj",
    osxLocale: "es_SV",
    dialectOf: "es-ES",
  },
  {
    id: "es-GT",
    name: "Spanish, Guatemala",
    editorCode: "esgt",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-GT",
    androidCode: "es-rGT",
    bcp47Code: "b+es+GT",
    osxCode: "es-GT.lproj",
    osxLocale: "es_GT",
    dialectOf: "es-ES",
  },
  {
    id: "es-HN",
    name: "Spanish, Honduras",
    editorCode: "eshn",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-HN",
    androidCode: "es-rHN",
    bcp47Code: "b+es+HN",
    osxCode: "es-HN.lproj",
    osxLocale: "es_HN",
    dialectOf: "es-ES",
  },
  {
    id: "es-419",
    name: "Spanish, Latin America",
    editorCode: "es419",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-419",
    androidCode: "es-r419",
    bcp47Code: "b+es+419",
    osxCode: "es-419.lproj",
    osxLocale: "es_419",
    dialectOf: "es-ES",
  },
  {
    id: "es-MX",
    name: "Spanish, Mexico",
    editorCode: "esmx",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-MX",
    androidCode: "es-rMX",
    bcp47Code: "b+es+MX",
    osxCode: "es-MX.lproj",
    osxLocale: "es_MX",
    dialectOf: "es-ES",
  },
  {
    id: "es-NI",
    name: "Spanish, Nicaragua",
    editorCode: "esni",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-NI",
    androidCode: "es-rNI",
    bcp47Code: "b+es+NI",
    osxCode: "es-NI.lproj",
    osxLocale: "es_NI",
    dialectOf: "es-ES",
  },
  {
    id: "es-PA",
    name: "Spanish, Panama",
    editorCode: "espa",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-PA",
    androidCode: "es-rPA",
    bcp47Code: "b+es+PA",
    osxCode: "es-PA.lproj",
    osxLocale: "es_PA",
    dialectOf: "es-ES",
  },
  {
    id: "es-PY",
    name: "Spanish, Paraguay",
    editorCode: "espy",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-PY",
    androidCode: "es-rPY",
    bcp47Code: "b+es+PY",
    osxCode: "es-PY.lproj",
    osxLocale: "es_PY",
    dialectOf: "es-ES",
  },
  {
    id: "es-PE",
    name: "Spanish, Peru",
    editorCode: "espe",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-PE",
    androidCode: "es-rPE",
    bcp47Code: "b+es+PE",
    osxCode: "es-PE.lproj",
    osxLocale: "es_PE",
    dialectOf: "es-ES",
  },
  {
    id: "es-PR",
    name: "Spanish, Puerto Rico",
    editorCode: "espr",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-PR",
    androidCode: "es-rPR",
    bcp47Code: "b+es+PR",
    osxCode: "es-PR.lproj",
    osxLocale: "es_PR",
    dialectOf: "es-ES",
  },
  {
    id: "es-US",
    name: "Spanish, United States",
    editorCode: "esus",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-US",
    androidCode: "es-rUS",
    bcp47Code: "b+es+US",
    osxCode: "es-US.lproj",
    osxLocale: "es_US",
    dialectOf: "es-ES",
  },
  {
    id: "es-UY",
    name: "Spanish, Uruguay",
    editorCode: "esuy",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-UY",
    androidCode: "es-rUY",
    bcp47Code: "b+es+UY",
    osxCode: "es-UY.lproj",
    osxLocale: "es_UY",
    dialectOf: "es-ES",
  },
  {
    id: "es-VE",
    name: "Spanish, Venezuela",
    editorCode: "esve",
    twoLettersCode: "es",
    threeLettersCode: "spa",
    locale: "es-VE",
    androidCode: "es-rVE",
    bcp47Code: "b+es+VE",
    osxCode: "es-VE.lproj",
    osxLocale: "es_VE",
    dialectOf: "es-ES",
  },
  {
    id: "su",
    name: "Sundanese",
    editorCode: "su",
    twoLettersCode: "su",
    threeLettersCode: "sun",
    locale: "su-ID",
    androidCode: "su-rID",
    bcp47Code: "b+su+ID",
    osxCode: "su.lproj",
    osxLocale: "su",
    dialectOf: null,
  },
  {
    id: "sw",
    name: "Swahili",
    editorCode: "sw",
    twoLettersCode: "sw",
    threeLettersCode: "swa",
    locale: "sw-KE",
    androidCode: "sw-rKE",
    bcp47Code: "b+sw+KE",
    osxCode: "sw.lproj",
    osxLocale: "sw",
    dialectOf: null,
  },
  {
    id: "sw-KE",
    name: "Swahili, Kenya",
    editorCode: "swke",
    twoLettersCode: "sw",
    threeLettersCode: "swa",
    locale: "sw-KE",
    androidCode: "sw-rKE",
    bcp47Code: "b+sw+KE",
    osxCode: "sw-KE.lproj",
    osxLocale: "sw_KE",
    dialectOf: "sw",
  },
  {
    id: "sw-TZ",
    name: "Swahili, Tanzania",
    editorCode: "swtz",
    twoLettersCode: "sw",
    threeLettersCode: "swa",
    locale: "sw-TZ",
    androidCode: "sw-rTZ",
    bcp47Code: "b+sw+TZ",
    osxCode: "sw-TZ.lproj",
    osxLocale: "sw_TZ",
    dialectOf: "sw",
  },
  {
    id: "ss",
    name: "Swati",
    editorCode: "ss",
    twoLettersCode: "ss",
    threeLettersCode: "ssw",
    locale: "ss-ZA",
    androidCode: "ss-rZA",
    bcp47Code: "b+ss+ZA",
    osxCode: "ss.lproj",
    osxLocale: "ss",
    dialectOf: null,
  },
  {
    id: "sv-SE",
    name: "Swedish",
    editorCode: "sv",
    twoLettersCode: "sv",
    threeLettersCode: "swe",
    locale: "sv-SE",
    androidCode: "sv-rSE",
    bcp47Code: "b+sv+SE",
    osxCode: "sv.lproj",
    osxLocale: "sv",
    dialectOf: null,
  },
  {
    id: "sv-FI",
    name: "Swedish, Finland",
    editorCode: "svfi",
    twoLettersCode: "sv",
    threeLettersCode: "swe",
    locale: "sv-FI",
    androidCode: "sv-rFI",
    bcp47Code: "b+sv+FI",
    osxCode: "sv-FI.lproj",
    osxLocale: "sv_FI",
    dialectOf: "sv-SE",
  },
  {
    id: "syc",
    name: "Syriac",
    editorCode: "syc",
    twoLettersCode: "syc",
    threeLettersCode: "syc",
    locale: "syc-SY",
    androidCode: "syc-rSY",
    bcp47Code: "b+syc+SY",
    osxCode: "syc.lproj",
    osxLocale: "syc",
    dialectOf: null,
  },
  {
    id: "tl",
    name: "Tagalog",
    editorCode: "tl",
    twoLettersCode: "tl",
    threeLettersCode: "tgl",
    locale: "tl-PH",
    androidCode: "tl-rPH",
    bcp47Code: "b+tl+PH",
    osxCode: "tl.lproj",
    osxLocale: "tl",
    dialectOf: null,
  },
  {
    id: "ty",
    name: "Tahitian",
    editorCode: "ty",
    twoLettersCode: "ty",
    threeLettersCode: "tah",
    locale: "ty-PF",
    androidCode: "ty-rPF",
    bcp47Code: "b+ty+PF",
    osxCode: "ty.lproj",
    osxLocale: "ty",
    dialectOf: null,
  },
  {
    id: "tg",
    name: "Tajik",
    editorCode: "tg",
    twoLettersCode: "tg",
    threeLettersCode: "tgk",
    locale: "tg-TJ",
    androidCode: "tg-rTJ",
    bcp47Code: "b+tg+TJ",
    osxCode: "tg.lproj",
    osxLocale: "tg",
    dialectOf: null,
  },
  {
    id: "tzl",
    name: "Talossan",
    editorCode: "tzl",
    twoLettersCode: "tzl",
    threeLettersCode: "tzl",
    locale: "tzl-TZL",
    androidCode: "tzl-rTZL",
    bcp47Code: "b+tzl+TZL",
    osxCode: "tzl.lproj",
    osxLocale: "tzl",
    dialectOf: null,
  },
  {
    id: "ta",
    name: "Tamil",
    editorCode: "ta",
    twoLettersCode: "ta",
    threeLettersCode: "tam",
    locale: "ta-IN",
    androidCode: "ta-rIN",
    bcp47Code: "b+ta+IN",
    osxCode: "ta.lproj",
    osxLocale: "ta",
    dialectOf: null,
  },
  {
    id: "tt-RU",
    name: "Tatar",
    editorCode: "ttru",
    twoLettersCode: "tt",
    threeLettersCode: "tat",
    locale: "tt-RU",
    androidCode: "tt-rRU",
    bcp47Code: "b+tt+RU",
    osxCode: "tt.lproj",
    osxLocale: "tt",
    dialectOf: null,
  },
  {
    id: "te",
    name: "Telugu",
    editorCode: "te",
    twoLettersCode: "te",
    threeLettersCode: "tel",
    locale: "te-IN",
    androidCode: "te-rIN",
    bcp47Code: "b+te+IN",
    osxCode: "te.lproj",
    osxLocale: "te",
    dialectOf: null,
  },
  {
    id: "kdh",
    name: "Tem (Kotokoli)",
    editorCode: "kdh",
    twoLettersCode: "kdh",
    threeLettersCode: "kdh",
    locale: "kdh-KDH",
    androidCode: "kdh-rKDH",
    bcp47Code: "b+kdh+KDH",
    osxCode: "kdh.lproj",
    osxLocale: "kdh",
    dialectOf: null,
  },
  {
    id: "th",
    name: "Thai",
    editorCode: "th",
    twoLettersCode: "th",
    threeLettersCode: "tha",
    locale: "th-TH",
    androidCode: "th-rTH",
    bcp47Code: "b+th+TH",
    osxCode: "th.lproj",
    osxLocale: "th",
    dialectOf: null,
  },
  {
    id: "bo-BT",
    name: "Tibetan",
    editorCode: "bobt",
    twoLettersCode: "bo",
    threeLettersCode: "tib",
    locale: "bo-BT",
    androidCode: "bo-rBT",
    bcp47Code: "b+bo+BT",
    osxCode: "bo.lproj",
    osxLocale: "bo",
    dialectOf: null,
  },
  {
    id: "ti",
    name: "Tigrinya",
    editorCode: "ti",
    twoLettersCode: "ti",
    threeLettersCode: "tir",
    locale: "ti-ER",
    androidCode: "ti-rER",
    bcp47Code: "b+ti+ER",
    osxCode: "ti.lproj",
    osxLocale: "ti",
    dialectOf: null,
  },
  {
    id: "ts",
    name: "Tsonga",
    editorCode: "ts",
    twoLettersCode: "ts",
    threeLettersCode: "tso",
    locale: "ts-ZA",
    androidCode: "ts-rZA",
    bcp47Code: "b+ts+ZA",
    osxCode: "ts.lproj",
    osxLocale: "ts",
    dialectOf: null,
  },
  {
    id: "tn",
    name: "Tswana",
    editorCode: "tn",
    twoLettersCode: "tn",
    threeLettersCode: "tsn",
    locale: "tn-ZA",
    androidCode: "tn-rZA",
    bcp47Code: "b+tn+ZA",
    osxCode: "tn.lproj",
    osxLocale: "tn",
    dialectOf: null,
  },
  {
    id: "tr",
    name: "Turkish",
    editorCode: "tr",
    twoLettersCode: "tr",
    threeLettersCode: "tur",
    locale: "tr-TR",
    androidCode: "tr-rTR",
    bcp47Code: "b+tr+TR",
    osxCode: "tr.lproj",
    osxLocale: "tr",
    dialectOf: null,
  },
  {
    id: "tr-CY",
    name: "Turkish, Cyprus",
    editorCode: "trcy",
    twoLettersCode: "tr",
    threeLettersCode: "tur",
    locale: "tr-CY",
    androidCode: "tr-rCY",
    bcp47Code: "b+tr+CY",
    osxCode: "tr-CY.lproj",
    osxLocale: "tr_CY",
    dialectOf: "tr",
  },
  {
    id: "tk",
    name: "Turkmen",
    editorCode: "tk",
    twoLettersCode: "tk",
    threeLettersCode: "tuk",
    locale: "tk-TM",
    androidCode: "tk-rTM",
    bcp47Code: "b+tk+TM",
    osxCode: "tk.lproj",
    osxLocale: "tk",
    dialectOf: null,
  },
  {
    id: "uk",
    name: "Ukrainian",
    editorCode: "uk",
    twoLettersCode: "uk",
    threeLettersCode: "ukr",
    locale: "uk-UA",
    androidCode: "uk-rUA",
    bcp47Code: "b+uk+UA",
    osxCode: "uk.lproj",
    osxLocale: "uk",
    dialectOf: null,
  },
  {
    id: "hsb-DE",
    name: "Upper Sorbian",
    editorCode: "hsbde",
    twoLettersCode: "hsb",
    threeLettersCode: "hsb",
    locale: "hsb-DE",
    androidCode: "hsb-rDE",
    bcp47Code: "b+hsb+DE",
    osxCode: "hsb.lproj",
    osxLocale: "hsb",
    dialectOf: null,
  },
  {
    id: "ur-IN",
    name: "Urdu (India)",
    editorCode: "urin",
    twoLettersCode: "ur",
    threeLettersCode: "urd",
    locale: "ur-IN",
    androidCode: "ur-rIN",
    bcp47Code: "b+ur+IN",
    osxCode: "ur-IN.lproj",
    osxLocale: "ur_IN",
    dialectOf: null,
  },
  {
    id: "ur-PK",
    name: "Urdu (Pakistan)",
    editorCode: "urpk",
    twoLettersCode: "ur",
    threeLettersCode: "urd",
    locale: "ur-PK",
    androidCode: "ur-rPK",
    bcp47Code: "b+ur+PK",
    osxCode: "ur.lproj",
    osxLocale: "ur",
    dialectOf: null,
  },
  {
    id: "ug",
    name: "Uyghur",
    editorCode: "ug",
    twoLettersCode: "ug",
    threeLettersCode: "uig",
    locale: "ug-CN",
    androidCode: "ug-rCN",
    bcp47Code: "b+ug+CN",
    osxCode: "ug.lproj",
    osxLocale: "ug",
    dialectOf: null,
  },
  {
    id: "uz",
    name: "Uzbek",
    editorCode: "uz",
    twoLettersCode: "uz",
    threeLettersCode: "uzb",
    locale: "uz-UZ",
    androidCode: "uz-rUZ",
    bcp47Code: "b+uz+UZ",
    osxCode: "uz.lproj",
    osxLocale: "uz",
    dialectOf: null,
  },
  {
    id: "val-ES",
    name: "Valencian",
    editorCode: "vales",
    twoLettersCode: "val",
    threeLettersCode: "val",
    locale: "val-ES",
    androidCode: "val-rES",
    bcp47Code: "b+val+ES",
    osxCode: "val.lproj",
    osxLocale: "val",
    dialectOf: null,
  },
  {
    id: "ve",
    name: "Venda",
    editorCode: "ve",
    twoLettersCode: "ve",
    threeLettersCode: "ven",
    locale: "ve-ZA",
    androidCode: "ve-rZA",
    bcp47Code: "b+ve+ZA",
    osxCode: "ve.lproj",
    osxLocale: "ve",
    dialectOf: null,
  },
  {
    id: "vec",
    name: "Venetian",
    editorCode: "vec",
    twoLettersCode: "vec",
    threeLettersCode: "vec",
    locale: "vec-IT",
    androidCode: "vec-rIT",
    bcp47Code: "b+vec+IT",
    osxCode: "vec.lproj",
    osxLocale: "vec",
    dialectOf: null,
  },
  {
    id: "vi",
    name: "Vietnamese",
    editorCode: "vi",
    twoLettersCode: "vi",
    threeLettersCode: "vie",
    locale: "vi-VN",
    androidCode: "vi-rVN",
    bcp47Code: "b+vi+VN",
    osxCode: "vi.lproj",
    osxLocale: "vi",
    dialectOf: null,
  },
  {
    id: "wa",
    name: "Walloon",
    editorCode: "wa",
    twoLettersCode: "wa",
    threeLettersCode: "wln",
    locale: "wa-BE",
    androidCode: "wa-rBE",
    bcp47Code: "b+wa+BE",
    osxCode: "wa.lproj",
    osxLocale: "wa",
    dialectOf: null,
  },
  {
    id: "cy",
    name: "Welsh",
    editorCode: "cy",
    twoLettersCode: "cy",
    threeLettersCode: "cym",
    locale: "cy-GB",
    androidCode: "cy-rGB",
    bcp47Code: "b+cy+GB",
    osxCode: "cy.lproj",
    osxLocale: "cy",
    dialectOf: null,
  },
  {
    id: "wo",
    name: "Wolof",
    editorCode: "wo",
    twoLettersCode: "wo",
    threeLettersCode: "wol",
    locale: "wo-SN",
    androidCode: "wo-rSN",
    bcp47Code: "b+wo+SN",
    osxCode: "wo.lproj",
    osxLocale: "wo",
    dialectOf: null,
  },
  {
    id: "xh",
    name: "Xhosa",
    editorCode: "xh",
    twoLettersCode: "xh",
    threeLettersCode: "xho",
    locale: "xh-ZA",
    androidCode: "xh-rZA",
    bcp47Code: "b+xh+ZA",
    osxCode: "xh.lproj",
    osxLocale: "xh",
    dialectOf: null,
  },
  {
    id: "yi",
    name: "Yiddish",
    editorCode: "yi",
    twoLettersCode: "yi",
    threeLettersCode: "yid",
    locale: "yi-DE",
    androidCode: "ji-rDE",
    bcp47Code: "b+yi+DE",
    osxCode: "yi.lproj",
    osxLocale: "yi",
    dialectOf: null,
  },
  {
    id: "yo",
    name: "Yoruba",
    editorCode: "yo",
    twoLettersCode: "yo",
    threeLettersCode: "yor",
    locale: "yo-NG",
    androidCode: "yo-rNG",
    bcp47Code: "b+yo+NG",
    osxCode: "yo.lproj",
    osxLocale: "yo",
    dialectOf: null,
  },
  {
    id: "zea",
    name: "Zeelandic",
    editorCode: "zea",
    twoLettersCode: "zea",
    threeLettersCode: "zea",
    locale: "zea-ZEA",
    androidCode: "zea-rZEA",
    bcp47Code: "b+zea+ZEA",
    osxCode: "zea.lproj",
    osxLocale: "zea",
    dialectOf: null,
  },
  {
    id: "zu",
    name: "Zulu",
    editorCode: "zu",
    twoLettersCode: "zu",
    threeLettersCode: "zul",
    locale: "zu-ZA",
    androidCode: "zu-rZA",
    bcp47Code: "b+zu+ZA",
    osxCode: "zu.lproj",
    osxLocale: "zu",
    dialectOf: null,
  },
] as const satisfies readonly CrowdinGlossaryLanguage[];

const crowdinByNormalizedId = new Map<string, CrowdinGlossaryLanguage>(
  CROWDIN_GLOSSARY_LANGUAGES.map((language) => [language.id.toLowerCase(), language]),
);
const crowdinByLocale = new Map<string, CrowdinGlossaryLanguage>();
for (const language of CROWDIN_GLOSSARY_LANGUAGES) {
  const locale = language.locale.toLowerCase();
  const existing = crowdinByLocale.get(locale);
  if (!existing || (existing.dialectOf !== null && language.dialectOf === null)) {
    crowdinByLocale.set(locale, language);
  }
}

function baseLanguage(locale: string): string {
  return locale.split("-")[0]?.toLowerCase() ?? locale.toLowerCase();
}

export function toCrowdinGlossaryLanguageId(locale: string): string {
  const normalized = locale.trim();
  const byLocale = crowdinByLocale.get(normalized.toLowerCase());
  if (byLocale) return byLocale.id;

  const byId = crowdinByNormalizedId.get(normalized.toLowerCase());
  if (byId) return byId.id;

  const base = baseLanguage(normalized);
  const baseMatches = CROWDIN_GLOSSARY_LANGUAGES.filter(
    (language) => baseLanguage(language.locale) === base,
  );
  const genericMatch = baseMatches.find((language) => language.locale.toLowerCase() === base);
  if (genericMatch) return genericMatch.id;
  if (baseMatches.length === 1) return baseMatches[0].id;

  // Custom Crowdin language IDs are absent from the built-in catalog.
  // Pass them through so glossary mutations and concordance keep working.
  return normalized;
}

export function toNativeGlossaryLocale(
  languageId: string,
  preferredLocales: readonly string[] = [],
) {
  const normalizedId = languageId.trim().toLowerCase();
  const preferred = preferredLocales.find(
    (locale) => toCrowdinGlossaryLanguageId(locale).toLowerCase() === normalizedId,
  );
  if (preferred) return preferred;

  return crowdinByNormalizedId.get(normalizedId)?.locale ?? languageId;
}
