allowBuilds:
  '@mongodb-js/zstd': false
  '@nestjs/core': false
  '@swc/core': false
  bun: true
  cbor-extract: false
  esbuild: false
  msw: false
  node-liblzma: false
  sharp: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.15
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  vite: "8.0.14"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
