import type { LocaleDetectionResult } from "./locale-detection";

export function generateI18nConfigYaml(detection: LocaleDetectionResult): string {
  const lines: string[] = [
    "# Generated by Hyperlocalise i18n setup wizard.",
    "# Review locale mappings and LLM provider settings before merging.",
    "locales:",
    `  source: ${detection.sourceLocale}`,
    "  targets:",
  ];

  if (detection.targetLocales.length === 0) {
    lines.push("    - es-ES");
  } else {
    for (const locale of detection.targetLocales) {
      lines.push(`    - ${locale}`);
    }
  }

  lines.push("", "buckets:");

  if (detection.groups.length === 0) {
    lines.push(
      "  translations:",
      "    files:",
      "      - from: locales/{{source}}.json",
      "        to: locales/{{target}}.json",
    );
  } else {
    for (const group of detection.groups) {
      lines.push(`  ${group.id}:`);
      lines.push("    files:");
      lines.push(`      - from: ${group.pathPattern.from}`);
      lines.push(`        to: ${group.pathPattern.to}`);
    }
  }

  lines.push(
    "",
    "llm:",
    "  profiles:",
    "    default:",
    "      provider: openai",
    "      model: gpt-5.2",
    "",
  );

  return lines.join("\n");
}
