import { Sandbox } from "@vercel/sandbox";

import type { I18nSetupMode } from "@/lib/agents/i18n-setup/merge-i18n-config";
import type { I18nSetupRequestedEventData } from "@/lib/agents/i18n-setup/i18n-setup-task";

type InstallationAuth = {
  token: string;
};

async function getInstallationOctokitForStep(installationId: number) {
  const { getInstallationOctokit } = await import("@/lib/agents/github/app");
  return getInstallationOctokit(installationId);
}

async function runSandboxCommand(
  sandboxId: string,
  command: string,
  args: string[],
  options?: { env?: Record<string, string> },
): Promise<{ exitCode: number; output: string }> {
  const sandbox = await Sandbox.get({ name: sandboxId });
  const result = await sandbox.runCommand({
    cmd: command,
    args,
    env: options?.env,
  });
  return {
    exitCode: result.exitCode,
    output: await result.output("both"),
  };
}

export async function createI18nSetupSandboxStep(input: {
  event: I18nSetupRequestedEventData;
  timeoutMs: number;
}): Promise<{ sandboxId: string }> {
  "use step";

  const octokit = await getInstallationOctokitForStep(input.event.installationId);
  const { token } = (await octokit.auth({ type: "installation" })) as InstallationAuth;
  const sandbox = await Sandbox.create({
    source: {
      depth: 1,
      password: token,
      revision: input.event.baseBranch,
      type: "git",
      url: `https://github.com/${input.event.repositoryFullName}.git`,
      username: "x-access-token",
    },
    timeout: input.timeoutMs,
  });

  return { sandboxId: sandbox.name };
}

export async function prepareI18nSetupSandboxStep(input: {
  event: I18nSetupRequestedEventData;
  sandboxId: string;
}): Promise<void> {
  "use step";

  const octokit = await getInstallationOctokitForStep(input.event.installationId);
  const { token } = (await octokit.auth({ type: "installation" })) as InstallationAuth;
  const remote = `https://github.com/${input.event.repositoryFullName}.git`;

  for (const [command, args, options] of [
    ["git", ["config", "user.name", "hyperlocalise[bot]"]],
    ["git", ["config", "user.email", "hyperlocalise[bot]@users.noreply.github.com"]],
    ["git", ["config", "credential.helper", "store"]],
    [
      "bash",
      [
        "-lc",
        `printf '%s\\n' "https://x-access-token:$GITHUB_TOKEN@github.com" > ~/.git-credentials`,
      ],
      { env: { GITHUB_TOKEN: token } },
    ],
    ["git", ["remote", "set-url", "origin", remote]],
  ] satisfies Array<[string, string[], { env?: Record<string, string> }?]>) {
    const result = await runSandboxCommand(input.sandboxId, command, args, options);
    if (result.exitCode !== 0) {
      throw new Error(`sandbox setup failed: ${result.output}`);
    }
  }
}

export async function commitPushAndCreateI18nSetupPullRequestStep(input: {
  event: I18nSetupRequestedEventData;
  sandboxId: string;
  branchName: string;
  summary: string;
  mode: I18nSetupMode;
  removeJsonc: boolean;
}): Promise<{ pullRequestUrl: string; pullRequestNumber: number }> {
  "use step";

  const octokit = await getInstallationOctokitForStep(input.event.installationId);
  const { data: repository } = await octokit.rest.repos.get({
    owner: input.event.repositoryOwner,
    repo: input.event.repositoryName,
  });

  if (repository.permissions?.push !== true) {
    throw new Error("The GitHub App installation does not have push access to this repository.");
  }

  const commitMessageByMode: Record<I18nSetupMode, string> = {
    create: "chore(i18n): add Hyperlocalise i18n.yml",
    update: "chore(i18n): update Hyperlocalise i18n.yml",
    convert: "chore(i18n): migrate i18n.jsonc to i18n.yml",
  };
  const commitMessage = commitMessageByMode[input.mode];
  const pullRequestTitle = commitMessage;

  const checkoutResult = await runSandboxCommand(input.sandboxId, "git", [
    "checkout",
    "-b",
    input.branchName,
  ]);
  if (checkoutResult.exitCode !== 0) {
    throw new Error(`git command failed: ${checkoutResult.output}`);
  }

  if (input.removeJsonc) {
    const removeJsoncResult = await runSandboxCommand(input.sandboxId, "git", [
      "rm",
      "-f",
      "i18n.jsonc",
    ]);
    if (removeJsoncResult.exitCode !== 0) {
      throw new Error(`git command failed: ${removeJsoncResult.output}`);
    }
  }

  for (const [command, args] of [
    ["git", ["add", "i18n.yml"]],
    ["git", ["commit", "-m", commitMessage]],
    ["git", ["push", "-u", "origin", input.branchName]],
  ] satisfies Array<[string, string[]]>) {
    const result = await runSandboxCommand(input.sandboxId, command, args);
    if (result.exitCode !== 0) {
      throw new Error(`git command failed: ${result.output}`);
    }
  }

  const prBodyIntroByMode: Record<I18nSetupMode, string> = {
    create:
      "This pull request adds an `i18n.yml` generated by the Hyperlocalise i18n setup wizard.",
    update: "This pull request updates `i18n.yml` with newly discovered locale files.",
    convert:
      "This pull request migrates `i18n.jsonc` to `i18n.yml` and removes the legacy JSONC config.",
  };
  const { data: pullRequest } = await octokit.rest.pulls.create({
    owner: input.event.repositoryOwner,
    repo: input.event.repositoryName,
    title: pullRequestTitle,
    head: input.branchName,
    base: input.event.baseBranch,
    body: [
      "## Hyperlocalise i18n setup",
      "",
      prBodyIntroByMode[input.mode],
      "",
      "Please review locale mappings and LLM provider settings before merging.",
      "",
      input.summary ? `Agent summary:\n\n${input.summary}` : "",
    ]
      .filter(Boolean)
      .join("\n"),
  });

  return {
    pullRequestUrl: pullRequest.html_url,
    pullRequestNumber: pullRequest.number,
  };
}
