package editor_export

import (
	"strings"
)

// SerializeTMX writes a TMX 1.4 document for the given rows.
func SerializeTMX(rows []Row) []byte {
	sourceLocale := "en"
	if len(rows) > 0 && rows[0].SourceLocale != "" {
		sourceLocale = rows[0].SourceLocale
	}

	var doc strings.Builder
	doc.Grow(300 + len(rows)*250)

	doc.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	doc.WriteString("<!--Generated by hyperlocalise.com-->\n")
	doc.WriteString("<tmx version=\"1.4\">\n")
	doc.WriteString("  <header creationtool=\"Hyperlocalise\" creationtoolversion=\"1\" segtype=\"sentence\" o-tmf=\"Hyperlocalise\" adminlang=\"en\" srclang=\"")
	doc.WriteString(escapeXML(sourceLocale))
	doc.WriteString("\" datatype=\"plaintext\"/>\n")
	doc.WriteString("  <body>\n")

	for _, row := range rows {
		tuid := escapeXML(row.Key)
		doc.WriteString("  <tu tuid=\"")
		doc.WriteString(tuid)
		doc.WriteString("\">\n")
		doc.WriteString("    <tuv xml:lang=\"")
		doc.WriteString(escapeXML(row.SourceLocale))
		doc.WriteString("\"><seg>")
		doc.WriteString(escapeXML(row.SourceText))
		doc.WriteString("</seg></tuv>\n")
		doc.WriteString("    <tuv xml:lang=\"")
		doc.WriteString(escapeXML(row.TargetLocale))
		doc.WriteString("\"><seg>")
		doc.WriteString(escapeXML(row.TargetText))
		doc.WriteString("</seg></tuv>\n")
		doc.WriteString("  </tu>\n")
	}

	doc.WriteString("  </body>\n")
	doc.WriteString("</tmx>\n")
	return []byte(doc.String())
}
