// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: hyperlocalise/translation/v1/translation.proto

package translationv1

import (
	v1 "github.com/quiet-circles/hyperlocalise/pkg/api/proto/hyperlocalise/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTranslationJobInput_FileFormat int32

const (
	FileTranslationJobInput_FILE_FORMAT_UNSPECIFIED FileTranslationJobInput_FileFormat = 0
	FileTranslationJobInput_FILE_FORMAT_XLIFF       FileTranslationJobInput_FileFormat = 1
	FileTranslationJobInput_FILE_FORMAT_JSON        FileTranslationJobInput_FileFormat = 2
	FileTranslationJobInput_FILE_FORMAT_PO          FileTranslationJobInput_FileFormat = 3
	FileTranslationJobInput_FILE_FORMAT_CSV         FileTranslationJobInput_FileFormat = 4
)

// Enum value maps for FileTranslationJobInput_FileFormat.
var (
	FileTranslationJobInput_FileFormat_name = map[int32]string{
		0: "FILE_FORMAT_UNSPECIFIED",
		1: "FILE_FORMAT_XLIFF",
		2: "FILE_FORMAT_JSON",
		3: "FILE_FORMAT_PO",
		4: "FILE_FORMAT_CSV",
	}
	FileTranslationJobInput_FileFormat_value = map[string]int32{
		"FILE_FORMAT_UNSPECIFIED": 0,
		"FILE_FORMAT_XLIFF":       1,
		"FILE_FORMAT_JSON":        2,
		"FILE_FORMAT_PO":          3,
		"FILE_FORMAT_CSV":         4,
	}
)

func (x FileTranslationJobInput_FileFormat) Enum() *FileTranslationJobInput_FileFormat {
	p := new(FileTranslationJobInput_FileFormat)
	*p = x
	return p
}

func (x FileTranslationJobInput_FileFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTranslationJobInput_FileFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_hyperlocalise_translation_v1_translation_proto_enumTypes[0].Descriptor()
}

func (FileTranslationJobInput_FileFormat) Type() protoreflect.EnumType {
	return &file_hyperlocalise_translation_v1_translation_proto_enumTypes[0]
}

func (x FileTranslationJobInput_FileFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTranslationJobInput_FileFormat.Descriptor instead.
func (FileTranslationJobInput_FileFormat) EnumDescriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{1, 0}
}

type TranslationJobError_Code int32

const (
	TranslationJobError_CODE_UNSPECIFIED        TranslationJobError_Code = 0
	TranslationJobError_CODE_INTERNAL           TranslationJobError_Code = 1
	TranslationJobError_CODE_INVALID_INPUT      TranslationJobError_Code = 2
	TranslationJobError_CODE_UNSUPPORTED_LOCALE TranslationJobError_Code = 3
	TranslationJobError_CODE_FILE_NOT_FOUND     TranslationJobError_Code = 4
	TranslationJobError_CODE_QUOTA_EXCEEDED     TranslationJobError_Code = 5
)

// Enum value maps for TranslationJobError_Code.
var (
	TranslationJobError_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_INTERNAL",
		2: "CODE_INVALID_INPUT",
		3: "CODE_UNSUPPORTED_LOCALE",
		4: "CODE_FILE_NOT_FOUND",
		5: "CODE_QUOTA_EXCEEDED",
	}
	TranslationJobError_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":        0,
		"CODE_INTERNAL":           1,
		"CODE_INVALID_INPUT":      2,
		"CODE_UNSUPPORTED_LOCALE": 3,
		"CODE_FILE_NOT_FOUND":     4,
		"CODE_QUOTA_EXCEEDED":     5,
	}
)

func (x TranslationJobError_Code) Enum() *TranslationJobError_Code {
	p := new(TranslationJobError_Code)
	*p = x
	return p
}

func (x TranslationJobError_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranslationJobError_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_hyperlocalise_translation_v1_translation_proto_enumTypes[1].Descriptor()
}

func (TranslationJobError_Code) Type() protoreflect.EnumType {
	return &file_hyperlocalise_translation_v1_translation_proto_enumTypes[1]
}

func (x TranslationJobError_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranslationJobError_Code.Descriptor instead.
func (TranslationJobError_Code) EnumDescriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{6, 0}
}

type TranslationJob_Type int32

const (
	TranslationJob_TYPE_UNSPECIFIED TranslationJob_Type = 0
	TranslationJob_TYPE_STRING      TranslationJob_Type = 1
	TranslationJob_TYPE_FILE        TranslationJob_Type = 2
)

// Enum value maps for TranslationJob_Type.
var (
	TranslationJob_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_STRING",
		2: "TYPE_FILE",
	}
	TranslationJob_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_STRING":      1,
		"TYPE_FILE":        2,
	}
)

func (x TranslationJob_Type) Enum() *TranslationJob_Type {
	p := new(TranslationJob_Type)
	*p = x
	return p
}

func (x TranslationJob_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranslationJob_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_hyperlocalise_translation_v1_translation_proto_enumTypes[2].Descriptor()
}

func (TranslationJob_Type) Type() protoreflect.EnumType {
	return &file_hyperlocalise_translation_v1_translation_proto_enumTypes[2]
}

func (x TranslationJob_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranslationJob_Type.Descriptor instead.
func (TranslationJob_Type) EnumDescriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{7, 0}
}

type TranslationJob_Status int32

const (
	TranslationJob_STATUS_UNSPECIFIED TranslationJob_Status = 0
	TranslationJob_STATUS_QUEUED      TranslationJob_Status = 1
	TranslationJob_STATUS_RUNNING     TranslationJob_Status = 2
	TranslationJob_STATUS_SUCCEEDED   TranslationJob_Status = 3
	TranslationJob_STATUS_FAILED      TranslationJob_Status = 4
)

// Enum value maps for TranslationJob_Status.
var (
	TranslationJob_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_QUEUED",
		2: "STATUS_RUNNING",
		3: "STATUS_SUCCEEDED",
		4: "STATUS_FAILED",
	}
	TranslationJob_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_QUEUED":      1,
		"STATUS_RUNNING":     2,
		"STATUS_SUCCEEDED":   3,
		"STATUS_FAILED":      4,
	}
)

func (x TranslationJob_Status) Enum() *TranslationJob_Status {
	p := new(TranslationJob_Status)
	*p = x
	return p
}

func (x TranslationJob_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranslationJob_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_hyperlocalise_translation_v1_translation_proto_enumTypes[3].Descriptor()
}

func (TranslationJob_Status) Type() protoreflect.EnumType {
	return &file_hyperlocalise_translation_v1_translation_proto_enumTypes[3]
}

func (x TranslationJob_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranslationJob_Status.Descriptor instead.
func (TranslationJob_Status) EnumDescriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{7, 1}
}

// Input for a translation job that translates in-memory text.
type StringTranslationJobInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceText    string                 `protobuf:"bytes,1,opt,name=source_text,json=sourceText,proto3" json:"source_text,omitempty"`
	SourceLocale  string                 `protobuf:"bytes,2,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	TargetLocales []string               `protobuf:"bytes,3,rep,name=target_locales,json=targetLocales,proto3" json:"target_locales,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional translator guidance describing product/UI context for the text.
	Context *string `protobuf:"bytes,5,opt,name=context,proto3,oneof" json:"context,omitempty"`
	// Optional maximum length constraint for each translated string.
	MaxLength     *int32 `protobuf:"varint,6,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTranslationJobInput) Reset() {
	*x = StringTranslationJobInput{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTranslationJobInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTranslationJobInput) ProtoMessage() {}

func (x *StringTranslationJobInput) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTranslationJobInput.ProtoReflect.Descriptor instead.
func (*StringTranslationJobInput) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{0}
}

func (x *StringTranslationJobInput) GetSourceText() string {
	if x != nil {
		return x.SourceText
	}
	return ""
}

func (x *StringTranslationJobInput) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *StringTranslationJobInput) GetTargetLocales() []string {
	if x != nil {
		return x.TargetLocales
	}
	return nil
}

func (x *StringTranslationJobInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StringTranslationJobInput) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *StringTranslationJobInput) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

// Input for a translation job that translates a file referenced by URI.
type FileTranslationJobInput struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	FileUri       string                             `protobuf:"bytes,1,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	FileFormat    FileTranslationJobInput_FileFormat `protobuf:"varint,2,opt,name=file_format,json=fileFormat,proto3,enum=hyperlocalise.translation.v1.FileTranslationJobInput_FileFormat" json:"file_format,omitempty"`
	SourceLocale  string                             `protobuf:"bytes,3,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	TargetLocales []string                           `protobuf:"bytes,4,rep,name=target_locales,json=targetLocales,proto3" json:"target_locales,omitempty"`
	Metadata      map[string]string                  `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTranslationJobInput) Reset() {
	*x = FileTranslationJobInput{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTranslationJobInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTranslationJobInput) ProtoMessage() {}

func (x *FileTranslationJobInput) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTranslationJobInput.ProtoReflect.Descriptor instead.
func (*FileTranslationJobInput) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{1}
}

func (x *FileTranslationJobInput) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *FileTranslationJobInput) GetFileFormat() FileTranslationJobInput_FileFormat {
	if x != nil {
		return x.FileFormat
	}
	return FileTranslationJobInput_FILE_FORMAT_UNSPECIFIED
}

func (x *FileTranslationJobInput) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *FileTranslationJobInput) GetTargetLocales() []string {
	if x != nil {
		return x.TargetLocales
	}
	return nil
}

func (x *FileTranslationJobInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Translated text for a single target locale.
type StringTranslation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTranslation) Reset() {
	*x = StringTranslation{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTranslation) ProtoMessage() {}

func (x *StringTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTranslation.ProtoReflect.Descriptor instead.
func (*StringTranslation) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{2}
}

func (x *StringTranslation) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *StringTranslation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Translated file location for a single target locale.
type FileTranslation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTranslation) Reset() {
	*x = FileTranslation{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTranslation) ProtoMessage() {}

func (x *FileTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTranslation.ProtoReflect.Descriptor instead.
func (*FileTranslation) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{3}
}

func (x *FileTranslation) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *FileTranslation) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

// Result payload for string-based translation jobs.
type StringTranslationJobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  []*StringTranslation   `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTranslationJobResult) Reset() {
	*x = StringTranslationJobResult{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTranslationJobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTranslationJobResult) ProtoMessage() {}

func (x *StringTranslationJobResult) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTranslationJobResult.ProtoReflect.Descriptor instead.
func (*StringTranslationJobResult) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{4}
}

func (x *StringTranslationJobResult) GetTranslations() []*StringTranslation {
	if x != nil {
		return x.Translations
	}
	return nil
}

// Result payload for file-based translation jobs.
type FileTranslationJobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  []*FileTranslation     `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTranslationJobResult) Reset() {
	*x = FileTranslationJobResult{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTranslationJobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTranslationJobResult) ProtoMessage() {}

func (x *FileTranslationJobResult) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTranslationJobResult.ProtoReflect.Descriptor instead.
func (*FileTranslationJobResult) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{5}
}

func (x *FileTranslationJobResult) GetTranslations() []*FileTranslation {
	if x != nil {
		return x.Translations
	}
	return nil
}

// Structured failure details for jobs that end in STATUS_FAILED.
type TranslationJobError struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          TranslationJobError_Code `protobuf:"varint,1,opt,name=code,proto3,enum=hyperlocalise.translation.v1.TranslationJobError_Code" json:"code,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string        `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationJobError) Reset() {
	*x = TranslationJobError{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationJobError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationJobError) ProtoMessage() {}

func (x *TranslationJobError) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationJobError.ProtoReflect.Descriptor instead.
func (*TranslationJobError) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{6}
}

func (x *TranslationJobError) GetCode() TranslationJobError_Code {
	if x != nil {
		return x.Code
	}
	return TranslationJobError_CODE_UNSPECIFIED
}

func (x *TranslationJobError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranslationJobError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Canonical translation job resource.
type TranslationJob struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Server-derived from the active input/result variant.
	Type        TranslationJob_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=hyperlocalise.translation.v1.TranslationJob_Type" json:"type,omitempty"`
	Status      TranslationJob_Status  `protobuf:"varint,4,opt,name=status,proto3,enum=hyperlocalise.translation.v1.TranslationJob_Status" json:"status,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Exactly one input variant must be set when the job is created.
	//
	// Types that are valid to be assigned to Input:
	//
	//	*TranslationJob_StringInput
	//	*TranslationJob_FileInput
	Input isTranslationJob_Input `protobuf_oneof:"input"`
	// Exactly one of the following is populated when the job is terminal.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*TranslationJob_StringResult
	//	*TranslationJob_FileResult
	//	*TranslationJob_Error
	Outcome       isTranslationJob_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationJob) Reset() {
	*x = TranslationJob{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationJob) ProtoMessage() {}

func (x *TranslationJob) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationJob.ProtoReflect.Descriptor instead.
func (*TranslationJob) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{7}
}

func (x *TranslationJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranslationJob) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TranslationJob) GetType() TranslationJob_Type {
	if x != nil {
		return x.Type
	}
	return TranslationJob_TYPE_UNSPECIFIED
}

func (x *TranslationJob) GetStatus() TranslationJob_Status {
	if x != nil {
		return x.Status
	}
	return TranslationJob_STATUS_UNSPECIFIED
}

func (x *TranslationJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TranslationJob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TranslationJob) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TranslationJob) GetInput() isTranslationJob_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TranslationJob) GetStringInput() *StringTranslationJobInput {
	if x != nil {
		if x, ok := x.Input.(*TranslationJob_StringInput); ok {
			return x.StringInput
		}
	}
	return nil
}

func (x *TranslationJob) GetFileInput() *FileTranslationJobInput {
	if x != nil {
		if x, ok := x.Input.(*TranslationJob_FileInput); ok {
			return x.FileInput
		}
	}
	return nil
}

func (x *TranslationJob) GetOutcome() isTranslationJob_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TranslationJob) GetStringResult() *StringTranslationJobResult {
	if x != nil {
		if x, ok := x.Outcome.(*TranslationJob_StringResult); ok {
			return x.StringResult
		}
	}
	return nil
}

func (x *TranslationJob) GetFileResult() *FileTranslationJobResult {
	if x != nil {
		if x, ok := x.Outcome.(*TranslationJob_FileResult); ok {
			return x.FileResult
		}
	}
	return nil
}

func (x *TranslationJob) GetError() *TranslationJobError {
	if x != nil {
		if x, ok := x.Outcome.(*TranslationJob_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTranslationJob_Input interface {
	isTranslationJob_Input()
}

type TranslationJob_StringInput struct {
	StringInput *StringTranslationJobInput `protobuf:"bytes,9,opt,name=string_input,json=stringInput,proto3,oneof"`
}

type TranslationJob_FileInput struct {
	FileInput *FileTranslationJobInput `protobuf:"bytes,10,opt,name=file_input,json=fileInput,proto3,oneof"`
}

func (*TranslationJob_StringInput) isTranslationJob_Input() {}

func (*TranslationJob_FileInput) isTranslationJob_Input() {}

type isTranslationJob_Outcome interface {
	isTranslationJob_Outcome()
}

type TranslationJob_StringResult struct {
	// Populated when status is STATUS_SUCCEEDED and type is TYPE_STRING.
	StringResult *StringTranslationJobResult `protobuf:"bytes,11,opt,name=string_result,json=stringResult,proto3,oneof"`
}

type TranslationJob_FileResult struct {
	// Populated when status is STATUS_SUCCEEDED and type is TYPE_FILE.
	FileResult *FileTranslationJobResult `protobuf:"bytes,12,opt,name=file_result,json=fileResult,proto3,oneof"`
}

type TranslationJob_Error struct {
	// Populated when status is STATUS_FAILED.
	Error *TranslationJobError `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

func (*TranslationJob_StringResult) isTranslationJob_Outcome() {}

func (*TranslationJob_FileResult) isTranslationJob_Outcome() {}

func (*TranslationJob_Error) isTranslationJob_Outcome() {}

// Creates a new translation job under a project.
type CreateTranslationJobRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*CreateTranslationJobRequest_StringInput
	//	*CreateTranslationJobRequest_FileInput
	Input         isCreateTranslationJobRequest_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationJobRequest) Reset() {
	*x = CreateTranslationJobRequest{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationJobRequest) ProtoMessage() {}

func (x *CreateTranslationJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationJobRequest.ProtoReflect.Descriptor instead.
func (*CreateTranslationJobRequest) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTranslationJobRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTranslationJobRequest) GetInput() isCreateTranslationJobRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateTranslationJobRequest) GetStringInput() *StringTranslationJobInput {
	if x != nil {
		if x, ok := x.Input.(*CreateTranslationJobRequest_StringInput); ok {
			return x.StringInput
		}
	}
	return nil
}

func (x *CreateTranslationJobRequest) GetFileInput() *FileTranslationJobInput {
	if x != nil {
		if x, ok := x.Input.(*CreateTranslationJobRequest_FileInput); ok {
			return x.FileInput
		}
	}
	return nil
}

type isCreateTranslationJobRequest_Input interface {
	isCreateTranslationJobRequest_Input()
}

type CreateTranslationJobRequest_StringInput struct {
	StringInput *StringTranslationJobInput `protobuf:"bytes,2,opt,name=string_input,json=stringInput,proto3,oneof"`
}

type CreateTranslationJobRequest_FileInput struct {
	FileInput *FileTranslationJobInput `protobuf:"bytes,3,opt,name=file_input,json=fileInput,proto3,oneof"`
}

func (*CreateTranslationJobRequest_StringInput) isCreateTranslationJobRequest_Input() {}

func (*CreateTranslationJobRequest_FileInput) isCreateTranslationJobRequest_Input() {}

// Returns the newly created translation job resource.
type CreateTranslationJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *TranslationJob        `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationJobResponse) Reset() {
	*x = CreateTranslationJobResponse{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationJobResponse) ProtoMessage() {}

func (x *CreateTranslationJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationJobResponse.ProtoReflect.Descriptor instead.
func (*CreateTranslationJobResponse) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTranslationJobResponse) GetJob() *TranslationJob {
	if x != nil {
		return x.Job
	}
	return nil
}

// Looks up the lightweight status view for a translation job.
type GetTranslationJobStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslationJob *v1.ResourceRef        `protobuf:"bytes,1,opt,name=translation_job,json=translationJob,proto3" json:"translation_job,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTranslationJobStatusRequest) Reset() {
	*x = GetTranslationJobStatusRequest{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationJobStatusRequest) ProtoMessage() {}

func (x *GetTranslationJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{10}
}

func (x *GetTranslationJobStatusRequest) GetTranslationJob() *v1.ResourceRef {
	if x != nil {
		return x.TranslationJob
	}
	return nil
}

// Looks up the full translation job resource, including results.
type GetTranslationJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslationJob *v1.ResourceRef        `protobuf:"bytes,1,opt,name=translation_job,json=translationJob,proto3" json:"translation_job,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTranslationJobRequest) Reset() {
	*x = GetTranslationJobRequest{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationJobRequest) ProtoMessage() {}

func (x *GetTranslationJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationJobRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationJobRequest) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{11}
}

func (x *GetTranslationJobRequest) GetTranslationJob() *v1.ResourceRef {
	if x != nil {
		return x.TranslationJob
	}
	return nil
}

// Lightweight status view used for polling job progress.
type TranslationJobStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId   string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Type        TranslationJob_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=hyperlocalise.translation.v1.TranslationJob_Type" json:"type,omitempty"`
	Status      TranslationJob_Status  `protobuf:"varint,4,opt,name=status,proto3,enum=hyperlocalise.translation.v1.TranslationJob_Status" json:"status,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Populated when status is STATUS_FAILED.
	Error         *TranslationJobError `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationJobStatus) Reset() {
	*x = TranslationJobStatus{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationJobStatus) ProtoMessage() {}

func (x *TranslationJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationJobStatus.ProtoReflect.Descriptor instead.
func (*TranslationJobStatus) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{12}
}

func (x *TranslationJobStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranslationJobStatus) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TranslationJobStatus) GetType() TranslationJob_Type {
	if x != nil {
		return x.Type
	}
	return TranslationJob_TYPE_UNSPECIFIED
}

func (x *TranslationJobStatus) GetStatus() TranslationJob_Status {
	if x != nil {
		return x.Status
	}
	return TranslationJob_STATUS_UNSPECIFIED
}

func (x *TranslationJobStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TranslationJobStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TranslationJobStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TranslationJobStatus) GetError() *TranslationJobError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Lists translation jobs for a project with optional filtering.
type ListTranslationJobsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Page      *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// Filter by job type. TYPE_UNSPECIFIED returns jobs of all types.
	Type TranslationJob_Type `protobuf:"varint,3,opt,name=type,proto3,enum=hyperlocalise.translation.v1.TranslationJob_Type" json:"type,omitempty"`
	// Filter by job status. STATUS_UNSPECIFIED returns jobs in all statuses.
	Status        TranslationJob_Status `protobuf:"varint,4,opt,name=status,proto3,enum=hyperlocalise.translation.v1.TranslationJob_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationJobsRequest) Reset() {
	*x = ListTranslationJobsRequest{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationJobsRequest) ProtoMessage() {}

func (x *ListTranslationJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationJobsRequest.ProtoReflect.Descriptor instead.
func (*ListTranslationJobsRequest) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{13}
}

func (x *ListTranslationJobsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListTranslationJobsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListTranslationJobsRequest) GetType() TranslationJob_Type {
	if x != nil {
		return x.Type
	}
	return TranslationJob_TYPE_UNSPECIFIED
}

func (x *ListTranslationJobsRequest) GetStatus() TranslationJob_Status {
	if x != nil {
		return x.Status
	}
	return TranslationJob_STATUS_UNSPECIFIED
}

// Paged list of translation jobs.
type ListTranslationJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*TranslationJob      `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationJobsResponse) Reset() {
	*x = ListTranslationJobsResponse{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationJobsResponse) ProtoMessage() {}

func (x *ListTranslationJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationJobsResponse.ProtoReflect.Descriptor instead.
func (*ListTranslationJobsResponse) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{14}
}

func (x *ListTranslationJobsResponse) GetJobs() []*TranslationJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListTranslationJobsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// Returns the lightweight job status view.
type GetTranslationJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *TranslationJobStatus  `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationJobStatusResponse) Reset() {
	*x = GetTranslationJobStatusResponse{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationJobStatusResponse) ProtoMessage() {}

func (x *GetTranslationJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTranslationJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{15}
}

func (x *GetTranslationJobStatusResponse) GetJob() *TranslationJobStatus {
	if x != nil {
		return x.Job
	}
	return nil
}

// Returns the full translation job resource.
type GetTranslationJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *TranslationJob        `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationJobResponse) Reset() {
	*x = GetTranslationJobResponse{}
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationJobResponse) ProtoMessage() {}

func (x *GetTranslationJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlocalise_translation_v1_translation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationJobResponse.ProtoReflect.Descriptor instead.
func (*GetTranslationJobResponse) Descriptor() ([]byte, []int) {
	return file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP(), []int{16}
}

func (x *GetTranslationJobResponse) GetJob() *TranslationJob {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_hyperlocalise_translation_v1_translation_proto protoreflect.FileDescriptor

const file_hyperlocalise_translation_v1_translation_proto_rawDesc = "" +
	"\n" +
	".hyperlocalise/translation/v1/translation.proto\x12\x1chyperlocalise.translation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$hyperlocalise/common/v1/common.proto\"\x86\x03\n" +
	"\x19StringTranslationJobInput\x12\x1f\n" +
	"\vsource_text\x18\x01 \x01(\tR\n" +
	"sourceText\x12#\n" +
	"\rsource_locale\x18\x02 \x01(\tR\fsourceLocale\x12%\n" +
	"\x0etarget_locales\x18\x03 \x03(\tR\rtargetLocales\x12a\n" +
	"\bmetadata\x18\x04 \x03(\v2E.hyperlocalise.translation.v1.StringTranslationJobInput.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\acontext\x18\x05 \x01(\tH\x00R\acontext\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x06 \x01(\x05H\x01R\tmaxLength\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_contextB\r\n" +
	"\v_max_length\"\x82\x04\n" +
	"\x17FileTranslationJobInput\x12\x19\n" +
	"\bfile_uri\x18\x01 \x01(\tR\afileUri\x12a\n" +
	"\vfile_format\x18\x02 \x01(\x0e2@.hyperlocalise.translation.v1.FileTranslationJobInput.FileFormatR\n" +
	"fileFormat\x12#\n" +
	"\rsource_locale\x18\x03 \x01(\tR\fsourceLocale\x12%\n" +
	"\x0etarget_locales\x18\x04 \x03(\tR\rtargetLocales\x12_\n" +
	"\bmetadata\x18\x05 \x03(\v2C.hyperlocalise.translation.v1.FileTranslationJobInput.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\n" +
	"FileFormat\x12\x1b\n" +
	"\x17FILE_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FILE_FORMAT_XLIFF\x10\x01\x12\x14\n" +
	"\x10FILE_FORMAT_JSON\x10\x02\x12\x12\n" +
	"\x0eFILE_FORMAT_PO\x10\x03\x12\x13\n" +
	"\x0fFILE_FORMAT_CSV\x10\x04\"?\n" +
	"\x11StringTranslation\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"D\n" +
	"\x0fFileTranslation\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\"q\n" +
	"\x1aStringTranslationJobResult\x12S\n" +
	"\ftranslations\x18\x01 \x03(\v2/.hyperlocalise.translation.v1.StringTranslationR\ftranslations\"m\n" +
	"\x18FileTranslationJobResult\x12Q\n" +
	"\ftranslations\x18\x01 \x03(\v2-.hyperlocalise.translation.v1.FileTranslationR\ftranslations\"\xaa\x03\n" +
	"\x13TranslationJobError\x12J\n" +
	"\x04code\x18\x01 \x01(\x0e26.hyperlocalise.translation.v1.TranslationJobError.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12X\n" +
	"\adetails\x18\x03 \x03(\v2>.hyperlocalise.translation.v1.TranslationJobError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCODE_INTERNAL\x10\x01\x12\x16\n" +
	"\x12CODE_INVALID_INPUT\x10\x02\x12\x1b\n" +
	"\x17CODE_UNSUPPORTED_LOCALE\x10\x03\x12\x17\n" +
	"\x13CODE_FILE_NOT_FOUND\x10\x04\x12\x17\n" +
	"\x13CODE_QUOTA_EXCEEDED\x10\x05\"\x89\b\n" +
	"\x0eTranslationJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12E\n" +
	"\x04type\x18\x03 \x01(\x0e21.hyperlocalise.translation.v1.TranslationJob.TypeR\x04type\x12K\n" +
	"\x06status\x18\x04 \x01(\x0e23.hyperlocalise.translation.v1.TranslationJob.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\\\n" +
	"\fstring_input\x18\t \x01(\v27.hyperlocalise.translation.v1.StringTranslationJobInputH\x00R\vstringInput\x12V\n" +
	"\n" +
	"file_input\x18\n" +
	" \x01(\v25.hyperlocalise.translation.v1.FileTranslationJobInputH\x00R\tfileInput\x12_\n" +
	"\rstring_result\x18\v \x01(\v28.hyperlocalise.translation.v1.StringTranslationJobResultH\x01R\fstringResult\x12Y\n" +
	"\vfile_result\x18\f \x01(\v26.hyperlocalise.translation.v1.FileTranslationJobResultH\x01R\n" +
	"fileResult\x12I\n" +
	"\x05error\x18\r \x01(\v21.hyperlocalise.translation.v1.TranslationJobErrorH\x01R\x05error\"<\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_STRING\x10\x01\x12\r\n" +
	"\tTYPE_FILE\x10\x02\"p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_QUEUED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x14\n" +
	"\x10STATUS_SUCCEEDED\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04B\a\n" +
	"\x05inputB\t\n" +
	"\aoutcome\"\xfb\x01\n" +
	"\x1bCreateTranslationJobRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\\\n" +
	"\fstring_input\x18\x02 \x01(\v27.hyperlocalise.translation.v1.StringTranslationJobInputH\x00R\vstringInput\x12V\n" +
	"\n" +
	"file_input\x18\x03 \x01(\v25.hyperlocalise.translation.v1.FileTranslationJobInputH\x00R\tfileInputB\a\n" +
	"\x05input\"^\n" +
	"\x1cCreateTranslationJobResponse\x12>\n" +
	"\x03job\x18\x01 \x01(\v2,.hyperlocalise.translation.v1.TranslationJobR\x03job\"o\n" +
	"\x1eGetTranslationJobStatusRequest\x12M\n" +
	"\x0ftranslation_job\x18\x01 \x01(\v2$.hyperlocalise.common.v1.ResourceRefR\x0etranslationJob\"i\n" +
	"\x18GetTranslationJobRequest\x12M\n" +
	"\x0ftranslation_job\x18\x01 \x01(\v2$.hyperlocalise.common.v1.ResourceRefR\x0etranslationJob\"\xd7\x03\n" +
	"\x14TranslationJobStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12E\n" +
	"\x04type\x18\x03 \x01(\x0e21.hyperlocalise.translation.v1.TranslationJob.TypeR\x04type\x12K\n" +
	"\x06status\x18\x04 \x01(\x0e23.hyperlocalise.translation.v1.TranslationJob.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12G\n" +
	"\x05error\x18\b \x01(\v21.hyperlocalise.translation.v1.TranslationJobErrorR\x05error\"\x89\x02\n" +
	"\x1aListTranslationJobsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x128\n" +
	"\x04page\x18\x02 \x01(\v2$.hyperlocalise.common.v1.PageRequestR\x04page\x12E\n" +
	"\x04type\x18\x03 \x01(\x0e21.hyperlocalise.translation.v1.TranslationJob.TypeR\x04type\x12K\n" +
	"\x06status\x18\x04 \x01(\x0e23.hyperlocalise.translation.v1.TranslationJob.StatusR\x06status\"\x9a\x01\n" +
	"\x1bListTranslationJobsResponse\x12@\n" +
	"\x04jobs\x18\x01 \x03(\v2,.hyperlocalise.translation.v1.TranslationJobR\x04jobs\x129\n" +
	"\x04page\x18\x02 \x01(\v2%.hyperlocalise.common.v1.PageResponseR\x04page\"g\n" +
	"\x1fGetTranslationJobStatusResponse\x12D\n" +
	"\x03job\x18\x01 \x01(\v22.hyperlocalise.translation.v1.TranslationJobStatusR\x03job\"[\n" +
	"\x19GetTranslationJobResponse\x12>\n" +
	"\x03job\x18\x01 \x01(\v2,.hyperlocalise.translation.v1.TranslationJobR\x03job2\xd1\x04\n" +
	"\x12TranslationService\x12\x8d\x01\n" +
	"\x14CreateTranslationJob\x129.hyperlocalise.translation.v1.CreateTranslationJobRequest\x1a:.hyperlocalise.translation.v1.CreateTranslationJobResponse\x12\x84\x01\n" +
	"\x11GetTranslationJob\x126.hyperlocalise.translation.v1.GetTranslationJobRequest\x1a7.hyperlocalise.translation.v1.GetTranslationJobResponse\x12\x96\x01\n" +
	"\x17GetTranslationJobStatus\x12<.hyperlocalise.translation.v1.GetTranslationJobStatusRequest\x1a=.hyperlocalise.translation.v1.GetTranslationJobStatusResponse\x12\x8a\x01\n" +
	"\x13ListTranslationJobs\x128.hyperlocalise.translation.v1.ListTranslationJobsRequest\x1a9.hyperlocalise.translation.v1.ListTranslationJobsResponseBaZ_github.com/quiet-circles/hyperlocalise/pkg/api/proto/hyperlocalise/translation/v1;translationv1b\x06proto3"

var (
	file_hyperlocalise_translation_v1_translation_proto_rawDescOnce sync.Once
	file_hyperlocalise_translation_v1_translation_proto_rawDescData []byte
)

func file_hyperlocalise_translation_v1_translation_proto_rawDescGZIP() []byte {
	file_hyperlocalise_translation_v1_translation_proto_rawDescOnce.Do(func() {
		file_hyperlocalise_translation_v1_translation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperlocalise_translation_v1_translation_proto_rawDesc), len(file_hyperlocalise_translation_v1_translation_proto_rawDesc)))
	})
	return file_hyperlocalise_translation_v1_translation_proto_rawDescData
}

var file_hyperlocalise_translation_v1_translation_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_hyperlocalise_translation_v1_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_hyperlocalise_translation_v1_translation_proto_goTypes = []any{
	(FileTranslationJobInput_FileFormat)(0), // 0: hyperlocalise.translation.v1.FileTranslationJobInput.FileFormat
	(TranslationJobError_Code)(0),           // 1: hyperlocalise.translation.v1.TranslationJobError.Code
	(TranslationJob_Type)(0),                // 2: hyperlocalise.translation.v1.TranslationJob.Type
	(TranslationJob_Status)(0),              // 3: hyperlocalise.translation.v1.TranslationJob.Status
	(*StringTranslationJobInput)(nil),       // 4: hyperlocalise.translation.v1.StringTranslationJobInput
	(*FileTranslationJobInput)(nil),         // 5: hyperlocalise.translation.v1.FileTranslationJobInput
	(*StringTranslation)(nil),               // 6: hyperlocalise.translation.v1.StringTranslation
	(*FileTranslation)(nil),                 // 7: hyperlocalise.translation.v1.FileTranslation
	(*StringTranslationJobResult)(nil),      // 8: hyperlocalise.translation.v1.StringTranslationJobResult
	(*FileTranslationJobResult)(nil),        // 9: hyperlocalise.translation.v1.FileTranslationJobResult
	(*TranslationJobError)(nil),             // 10: hyperlocalise.translation.v1.TranslationJobError
	(*TranslationJob)(nil),                  // 11: hyperlocalise.translation.v1.TranslationJob
	(*CreateTranslationJobRequest)(nil),     // 12: hyperlocalise.translation.v1.CreateTranslationJobRequest
	(*CreateTranslationJobResponse)(nil),    // 13: hyperlocalise.translation.v1.CreateTranslationJobResponse
	(*GetTranslationJobStatusRequest)(nil),  // 14: hyperlocalise.translation.v1.GetTranslationJobStatusRequest
	(*GetTranslationJobRequest)(nil),        // 15: hyperlocalise.translation.v1.GetTranslationJobRequest
	(*TranslationJobStatus)(nil),            // 16: hyperlocalise.translation.v1.TranslationJobStatus
	(*ListTranslationJobsRequest)(nil),      // 17: hyperlocalise.translation.v1.ListTranslationJobsRequest
	(*ListTranslationJobsResponse)(nil),     // 18: hyperlocalise.translation.v1.ListTranslationJobsResponse
	(*GetTranslationJobStatusResponse)(nil), // 19: hyperlocalise.translation.v1.GetTranslationJobStatusResponse
	(*GetTranslationJobResponse)(nil),       // 20: hyperlocalise.translation.v1.GetTranslationJobResponse
	nil,                                     // 21: hyperlocalise.translation.v1.StringTranslationJobInput.MetadataEntry
	nil,                                     // 22: hyperlocalise.translation.v1.FileTranslationJobInput.MetadataEntry
	nil,                                     // 23: hyperlocalise.translation.v1.TranslationJobError.DetailsEntry
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
	(*v1.ResourceRef)(nil),                  // 25: hyperlocalise.common.v1.ResourceRef
	(*v1.PageRequest)(nil),                  // 26: hyperlocalise.common.v1.PageRequest
	(*v1.PageResponse)(nil),                 // 27: hyperlocalise.common.v1.PageResponse
}
var file_hyperlocalise_translation_v1_translation_proto_depIdxs = []int32{
	21, // 0: hyperlocalise.translation.v1.StringTranslationJobInput.metadata:type_name -> hyperlocalise.translation.v1.StringTranslationJobInput.MetadataEntry
	0,  // 1: hyperlocalise.translation.v1.FileTranslationJobInput.file_format:type_name -> hyperlocalise.translation.v1.FileTranslationJobInput.FileFormat
	22, // 2: hyperlocalise.translation.v1.FileTranslationJobInput.metadata:type_name -> hyperlocalise.translation.v1.FileTranslationJobInput.MetadataEntry
	6,  // 3: hyperlocalise.translation.v1.StringTranslationJobResult.translations:type_name -> hyperlocalise.translation.v1.StringTranslation
	7,  // 4: hyperlocalise.translation.v1.FileTranslationJobResult.translations:type_name -> hyperlocalise.translation.v1.FileTranslation
	1,  // 5: hyperlocalise.translation.v1.TranslationJobError.code:type_name -> hyperlocalise.translation.v1.TranslationJobError.Code
	23, // 6: hyperlocalise.translation.v1.TranslationJobError.details:type_name -> hyperlocalise.translation.v1.TranslationJobError.DetailsEntry
	2,  // 7: hyperlocalise.translation.v1.TranslationJob.type:type_name -> hyperlocalise.translation.v1.TranslationJob.Type
	3,  // 8: hyperlocalise.translation.v1.TranslationJob.status:type_name -> hyperlocalise.translation.v1.TranslationJob.Status
	24, // 9: hyperlocalise.translation.v1.TranslationJob.created_at:type_name -> google.protobuf.Timestamp
	24, // 10: hyperlocalise.translation.v1.TranslationJob.updated_at:type_name -> google.protobuf.Timestamp
	24, // 11: hyperlocalise.translation.v1.TranslationJob.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 12: hyperlocalise.translation.v1.TranslationJob.string_input:type_name -> hyperlocalise.translation.v1.StringTranslationJobInput
	5,  // 13: hyperlocalise.translation.v1.TranslationJob.file_input:type_name -> hyperlocalise.translation.v1.FileTranslationJobInput
	8,  // 14: hyperlocalise.translation.v1.TranslationJob.string_result:type_name -> hyperlocalise.translation.v1.StringTranslationJobResult
	9,  // 15: hyperlocalise.translation.v1.TranslationJob.file_result:type_name -> hyperlocalise.translation.v1.FileTranslationJobResult
	10, // 16: hyperlocalise.translation.v1.TranslationJob.error:type_name -> hyperlocalise.translation.v1.TranslationJobError
	4,  // 17: hyperlocalise.translation.v1.CreateTranslationJobRequest.string_input:type_name -> hyperlocalise.translation.v1.StringTranslationJobInput
	5,  // 18: hyperlocalise.translation.v1.CreateTranslationJobRequest.file_input:type_name -> hyperlocalise.translation.v1.FileTranslationJobInput
	11, // 19: hyperlocalise.translation.v1.CreateTranslationJobResponse.job:type_name -> hyperlocalise.translation.v1.TranslationJob
	25, // 20: hyperlocalise.translation.v1.GetTranslationJobStatusRequest.translation_job:type_name -> hyperlocalise.common.v1.ResourceRef
	25, // 21: hyperlocalise.translation.v1.GetTranslationJobRequest.translation_job:type_name -> hyperlocalise.common.v1.ResourceRef
	2,  // 22: hyperlocalise.translation.v1.TranslationJobStatus.type:type_name -> hyperlocalise.translation.v1.TranslationJob.Type
	3,  // 23: hyperlocalise.translation.v1.TranslationJobStatus.status:type_name -> hyperlocalise.translation.v1.TranslationJob.Status
	24, // 24: hyperlocalise.translation.v1.TranslationJobStatus.created_at:type_name -> google.protobuf.Timestamp
	24, // 25: hyperlocalise.translation.v1.TranslationJobStatus.updated_at:type_name -> google.protobuf.Timestamp
	24, // 26: hyperlocalise.translation.v1.TranslationJobStatus.completed_at:type_name -> google.protobuf.Timestamp
	10, // 27: hyperlocalise.translation.v1.TranslationJobStatus.error:type_name -> hyperlocalise.translation.v1.TranslationJobError
	26, // 28: hyperlocalise.translation.v1.ListTranslationJobsRequest.page:type_name -> hyperlocalise.common.v1.PageRequest
	2,  // 29: hyperlocalise.translation.v1.ListTranslationJobsRequest.type:type_name -> hyperlocalise.translation.v1.TranslationJob.Type
	3,  // 30: hyperlocalise.translation.v1.ListTranslationJobsRequest.status:type_name -> hyperlocalise.translation.v1.TranslationJob.Status
	11, // 31: hyperlocalise.translation.v1.ListTranslationJobsResponse.jobs:type_name -> hyperlocalise.translation.v1.TranslationJob
	27, // 32: hyperlocalise.translation.v1.ListTranslationJobsResponse.page:type_name -> hyperlocalise.common.v1.PageResponse
	16, // 33: hyperlocalise.translation.v1.GetTranslationJobStatusResponse.job:type_name -> hyperlocalise.translation.v1.TranslationJobStatus
	11, // 34: hyperlocalise.translation.v1.GetTranslationJobResponse.job:type_name -> hyperlocalise.translation.v1.TranslationJob
	12, // 35: hyperlocalise.translation.v1.TranslationService.CreateTranslationJob:input_type -> hyperlocalise.translation.v1.CreateTranslationJobRequest
	15, // 36: hyperlocalise.translation.v1.TranslationService.GetTranslationJob:input_type -> hyperlocalise.translation.v1.GetTranslationJobRequest
	14, // 37: hyperlocalise.translation.v1.TranslationService.GetTranslationJobStatus:input_type -> hyperlocalise.translation.v1.GetTranslationJobStatusRequest
	17, // 38: hyperlocalise.translation.v1.TranslationService.ListTranslationJobs:input_type -> hyperlocalise.translation.v1.ListTranslationJobsRequest
	13, // 39: hyperlocalise.translation.v1.TranslationService.CreateTranslationJob:output_type -> hyperlocalise.translation.v1.CreateTranslationJobResponse
	20, // 40: hyperlocalise.translation.v1.TranslationService.GetTranslationJob:output_type -> hyperlocalise.translation.v1.GetTranslationJobResponse
	19, // 41: hyperlocalise.translation.v1.TranslationService.GetTranslationJobStatus:output_type -> hyperlocalise.translation.v1.GetTranslationJobStatusResponse
	18, // 42: hyperlocalise.translation.v1.TranslationService.ListTranslationJobs:output_type -> hyperlocalise.translation.v1.ListTranslationJobsResponse
	39, // [39:43] is the sub-list for method output_type
	35, // [35:39] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_hyperlocalise_translation_v1_translation_proto_init() }
func file_hyperlocalise_translation_v1_translation_proto_init() {
	if File_hyperlocalise_translation_v1_translation_proto != nil {
		return
	}
	file_hyperlocalise_translation_v1_translation_proto_msgTypes[0].OneofWrappers = []any{}
	file_hyperlocalise_translation_v1_translation_proto_msgTypes[7].OneofWrappers = []any{
		(*TranslationJob_StringInput)(nil),
		(*TranslationJob_FileInput)(nil),
		(*TranslationJob_StringResult)(nil),
		(*TranslationJob_FileResult)(nil),
		(*TranslationJob_Error)(nil),
	}
	file_hyperlocalise_translation_v1_translation_proto_msgTypes[8].OneofWrappers = []any{
		(*CreateTranslationJobRequest_StringInput)(nil),
		(*CreateTranslationJobRequest_FileInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperlocalise_translation_v1_translation_proto_rawDesc), len(file_hyperlocalise_translation_v1_translation_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyperlocalise_translation_v1_translation_proto_goTypes,
		DependencyIndexes: file_hyperlocalise_translation_v1_translation_proto_depIdxs,
		EnumInfos:         file_hyperlocalise_translation_v1_translation_proto_enumTypes,
		MessageInfos:      file_hyperlocalise_translation_v1_translation_proto_msgTypes,
	}.Build()
	File_hyperlocalise_translation_v1_translation_proto = out.File
	file_hyperlocalise_translation_v1_translation_proto_goTypes = nil
	file_hyperlocalise_translation_v1_translation_proto_depIdxs = nil
}
