// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: hyperlocalise/translation/v1/translation.proto

package translationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslationService_CreateTranslationJob_FullMethodName          = "/hyperlocalise.translation.v1.TranslationService/CreateTranslationJob"
	TranslationService_CreateTranslationFileUpload_FullMethodName   = "/hyperlocalise.translation.v1.TranslationService/CreateTranslationFileUpload"
	TranslationService_FinalizeTranslationFileUpload_FullMethodName = "/hyperlocalise.translation.v1.TranslationService/FinalizeTranslationFileUpload"
	TranslationService_GetTranslationFile_FullMethodName            = "/hyperlocalise.translation.v1.TranslationService/GetTranslationFile"
	TranslationService_ListTranslationFileTree_FullMethodName       = "/hyperlocalise.translation.v1.TranslationService/ListTranslationFileTree"
	TranslationService_GetTranslationFileDownload_FullMethodName    = "/hyperlocalise.translation.v1.TranslationService/GetTranslationFileDownload"
	TranslationService_GetTranslationJob_FullMethodName             = "/hyperlocalise.translation.v1.TranslationService/GetTranslationJob"
	TranslationService_GetTranslationJobStatus_FullMethodName       = "/hyperlocalise.translation.v1.TranslationService/GetTranslationJobStatus"
	TranslationService_ListTranslationJobs_FullMethodName           = "/hyperlocalise.translation.v1.TranslationService/ListTranslationJobs"
)

// TranslationServiceClient is the client API for TranslationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Translation job management API.
type TranslationServiceClient interface {
	CreateTranslationJob(ctx context.Context, in *CreateTranslationJobRequest, opts ...grpc.CallOption) (*CreateTranslationJobResponse, error)
	CreateTranslationFileUpload(ctx context.Context, in *CreateTranslationFileUploadRequest, opts ...grpc.CallOption) (*CreateTranslationFileUploadResponse, error)
	FinalizeTranslationFileUpload(ctx context.Context, in *FinalizeTranslationFileUploadRequest, opts ...grpc.CallOption) (*FinalizeTranslationFileUploadResponse, error)
	GetTranslationFile(ctx context.Context, in *GetTranslationFileRequest, opts ...grpc.CallOption) (*GetTranslationFileResponse, error)
	ListTranslationFileTree(ctx context.Context, in *ListTranslationFileTreeRequest, opts ...grpc.CallOption) (*ListTranslationFileTreeResponse, error)
	GetTranslationFileDownload(ctx context.Context, in *GetTranslationFileDownloadRequest, opts ...grpc.CallOption) (*GetTranslationFileDownloadResponse, error)
	GetTranslationJob(ctx context.Context, in *GetTranslationJobRequest, opts ...grpc.CallOption) (*GetTranslationJobResponse, error)
	GetTranslationJobStatus(ctx context.Context, in *GetTranslationJobStatusRequest, opts ...grpc.CallOption) (*GetTranslationJobStatusResponse, error)
	ListTranslationJobs(ctx context.Context, in *ListTranslationJobsRequest, opts ...grpc.CallOption) (*ListTranslationJobsResponse, error)
}

type translationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationServiceClient(cc grpc.ClientConnInterface) TranslationServiceClient {
	return &translationServiceClient{cc}
}

func (c *translationServiceClient) CreateTranslationJob(ctx context.Context, in *CreateTranslationJobRequest, opts ...grpc.CallOption) (*CreateTranslationJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTranslationJobResponse)
	err := c.cc.Invoke(ctx, TranslationService_CreateTranslationJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) CreateTranslationFileUpload(ctx context.Context, in *CreateTranslationFileUploadRequest, opts ...grpc.CallOption) (*CreateTranslationFileUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTranslationFileUploadResponse)
	err := c.cc.Invoke(ctx, TranslationService_CreateTranslationFileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) FinalizeTranslationFileUpload(ctx context.Context, in *FinalizeTranslationFileUploadRequest, opts ...grpc.CallOption) (*FinalizeTranslationFileUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeTranslationFileUploadResponse)
	err := c.cc.Invoke(ctx, TranslationService_FinalizeTranslationFileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) GetTranslationFile(ctx context.Context, in *GetTranslationFileRequest, opts ...grpc.CallOption) (*GetTranslationFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranslationFileResponse)
	err := c.cc.Invoke(ctx, TranslationService_GetTranslationFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) ListTranslationFileTree(ctx context.Context, in *ListTranslationFileTreeRequest, opts ...grpc.CallOption) (*ListTranslationFileTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTranslationFileTreeResponse)
	err := c.cc.Invoke(ctx, TranslationService_ListTranslationFileTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) GetTranslationFileDownload(ctx context.Context, in *GetTranslationFileDownloadRequest, opts ...grpc.CallOption) (*GetTranslationFileDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranslationFileDownloadResponse)
	err := c.cc.Invoke(ctx, TranslationService_GetTranslationFileDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) GetTranslationJob(ctx context.Context, in *GetTranslationJobRequest, opts ...grpc.CallOption) (*GetTranslationJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranslationJobResponse)
	err := c.cc.Invoke(ctx, TranslationService_GetTranslationJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) GetTranslationJobStatus(ctx context.Context, in *GetTranslationJobStatusRequest, opts ...grpc.CallOption) (*GetTranslationJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranslationJobStatusResponse)
	err := c.cc.Invoke(ctx, TranslationService_GetTranslationJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) ListTranslationJobs(ctx context.Context, in *ListTranslationJobsRequest, opts ...grpc.CallOption) (*ListTranslationJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTranslationJobsResponse)
	err := c.cc.Invoke(ctx, TranslationService_ListTranslationJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslationServiceServer is the server API for TranslationService service.
// All implementations must embed UnimplementedTranslationServiceServer
// for forward compatibility.
//
// Translation job management API.
type TranslationServiceServer interface {
	CreateTranslationJob(context.Context, *CreateTranslationJobRequest) (*CreateTranslationJobResponse, error)
	CreateTranslationFileUpload(context.Context, *CreateTranslationFileUploadRequest) (*CreateTranslationFileUploadResponse, error)
	FinalizeTranslationFileUpload(context.Context, *FinalizeTranslationFileUploadRequest) (*FinalizeTranslationFileUploadResponse, error)
	GetTranslationFile(context.Context, *GetTranslationFileRequest) (*GetTranslationFileResponse, error)
	ListTranslationFileTree(context.Context, *ListTranslationFileTreeRequest) (*ListTranslationFileTreeResponse, error)
	GetTranslationFileDownload(context.Context, *GetTranslationFileDownloadRequest) (*GetTranslationFileDownloadResponse, error)
	GetTranslationJob(context.Context, *GetTranslationJobRequest) (*GetTranslationJobResponse, error)
	GetTranslationJobStatus(context.Context, *GetTranslationJobStatusRequest) (*GetTranslationJobStatusResponse, error)
	ListTranslationJobs(context.Context, *ListTranslationJobsRequest) (*ListTranslationJobsResponse, error)
	mustEmbedUnimplementedTranslationServiceServer()
}

// UnimplementedTranslationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslationServiceServer struct{}

func (UnimplementedTranslationServiceServer) CreateTranslationJob(context.Context, *CreateTranslationJobRequest) (*CreateTranslationJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTranslationJob not implemented")
}
func (UnimplementedTranslationServiceServer) CreateTranslationFileUpload(context.Context, *CreateTranslationFileUploadRequest) (*CreateTranslationFileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTranslationFileUpload not implemented")
}
func (UnimplementedTranslationServiceServer) FinalizeTranslationFileUpload(context.Context, *FinalizeTranslationFileUploadRequest) (*FinalizeTranslationFileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeTranslationFileUpload not implemented")
}
func (UnimplementedTranslationServiceServer) GetTranslationFile(context.Context, *GetTranslationFileRequest) (*GetTranslationFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranslationFile not implemented")
}
func (UnimplementedTranslationServiceServer) ListTranslationFileTree(context.Context, *ListTranslationFileTreeRequest) (*ListTranslationFileTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTranslationFileTree not implemented")
}
func (UnimplementedTranslationServiceServer) GetTranslationFileDownload(context.Context, *GetTranslationFileDownloadRequest) (*GetTranslationFileDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranslationFileDownload not implemented")
}
func (UnimplementedTranslationServiceServer) GetTranslationJob(context.Context, *GetTranslationJobRequest) (*GetTranslationJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranslationJob not implemented")
}
func (UnimplementedTranslationServiceServer) GetTranslationJobStatus(context.Context, *GetTranslationJobStatusRequest) (*GetTranslationJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranslationJobStatus not implemented")
}
func (UnimplementedTranslationServiceServer) ListTranslationJobs(context.Context, *ListTranslationJobsRequest) (*ListTranslationJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTranslationJobs not implemented")
}
func (UnimplementedTranslationServiceServer) mustEmbedUnimplementedTranslationServiceServer() {}
func (UnimplementedTranslationServiceServer) testEmbeddedByValue()                            {}

// UnsafeTranslationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationServiceServer will
// result in compilation errors.
type UnsafeTranslationServiceServer interface {
	mustEmbedUnimplementedTranslationServiceServer()
}

func RegisterTranslationServiceServer(s grpc.ServiceRegistrar, srv TranslationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTranslationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslationService_ServiceDesc, srv)
}

func _TranslationService_CreateTranslationJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTranslationJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).CreateTranslationJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_CreateTranslationJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).CreateTranslationJob(ctx, req.(*CreateTranslationJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_CreateTranslationFileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTranslationFileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).CreateTranslationFileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_CreateTranslationFileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).CreateTranslationFileUpload(ctx, req.(*CreateTranslationFileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_FinalizeTranslationFileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeTranslationFileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).FinalizeTranslationFileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_FinalizeTranslationFileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).FinalizeTranslationFileUpload(ctx, req.(*FinalizeTranslationFileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_GetTranslationFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranslationFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).GetTranslationFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_GetTranslationFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).GetTranslationFile(ctx, req.(*GetTranslationFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_ListTranslationFileTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTranslationFileTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).ListTranslationFileTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_ListTranslationFileTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).ListTranslationFileTree(ctx, req.(*ListTranslationFileTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_GetTranslationFileDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranslationFileDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).GetTranslationFileDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_GetTranslationFileDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).GetTranslationFileDownload(ctx, req.(*GetTranslationFileDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_GetTranslationJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranslationJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).GetTranslationJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_GetTranslationJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).GetTranslationJob(ctx, req.(*GetTranslationJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_GetTranslationJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranslationJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).GetTranslationJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_GetTranslationJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).GetTranslationJobStatus(ctx, req.(*GetTranslationJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_ListTranslationJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTranslationJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).ListTranslationJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_ListTranslationJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).ListTranslationJobs(ctx, req.(*ListTranslationJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranslationService_ServiceDesc is the grpc.ServiceDesc for TranslationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperlocalise.translation.v1.TranslationService",
	HandlerType: (*TranslationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTranslationJob",
			Handler:    _TranslationService_CreateTranslationJob_Handler,
		},
		{
			MethodName: "CreateTranslationFileUpload",
			Handler:    _TranslationService_CreateTranslationFileUpload_Handler,
		},
		{
			MethodName: "FinalizeTranslationFileUpload",
			Handler:    _TranslationService_FinalizeTranslationFileUpload_Handler,
		},
		{
			MethodName: "GetTranslationFile",
			Handler:    _TranslationService_GetTranslationFile_Handler,
		},
		{
			MethodName: "ListTranslationFileTree",
			Handler:    _TranslationService_ListTranslationFileTree_Handler,
		},
		{
			MethodName: "GetTranslationFileDownload",
			Handler:    _TranslationService_GetTranslationFileDownload_Handler,
		},
		{
			MethodName: "GetTranslationJob",
			Handler:    _TranslationService_GetTranslationJob_Handler,
		},
		{
			MethodName: "GetTranslationJobStatus",
			Handler:    _TranslationService_GetTranslationJobStatus_Handler,
		},
		{
			MethodName: "ListTranslationJobs",
			Handler:    _TranslationService_ListTranslationJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyperlocalise/translation/v1/translation.proto",
}
