/*
 * Copyright (c) 2026 Hyperlocalise Pty Ltd
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in this application's LICENSE file.
 *
 * Change Date: Four years after publication of the applicable version.
 *
 * On the Change Date, in accordance with the Business Source License, use
 * of this software will be governed by the GNU General Public License
 * Version 2.0 or later.
 */
// Integration catalog: add or edit integrations in integration-catalog.ts and integration-catalog.copy.ts.
import type { IntegrationCatalogEntry } from "@/lib/integrations/integration-catalog.types";
import type { IntegrationCatalogSlug } from "@/lib/integrations/integration-catalog.copy";

export const integrationCatalogEntries: IntegrationCatalogEntry[] = [
  {
    slug: "github",
    category: "source-control",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    iconKey: "github",
    websiteUrl: "https://github.com",
    relatedSlugs: ["gitlab", "slack", "crowdin"],
    keywords: ["GitHub localization", "GitHub translation workflow", "Hyperlocalise GitHub"],
  },
  {
    slug: "gitlab",
    category: "source-control",
    status: "coming-soon",
    type: "partner",
    marketing: true,
    workspace: true,
    iconKey: "gitlab",
    websiteUrl: "https://gitlab.com",
    relatedSlugs: ["github", "slack", "jira"],
    keywords: ["GitLab localization", "GitLab translation workflow"],
  },
  {
    slug: "slack",
    category: "collaboration",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/slack-logo.svg",
    websiteUrl: "https://slack.com",
    relatedSlugs: ["github", "jira", "linear"],
    keywords: ["Slack localization", "translation review Slack", "Hyperlocalise Slack"],
  },
  {
    slug: "microsoft-teams",
    category: "collaboration",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    logoSrc: "/images/microsoft-teams-logo.svg",
    websiteUrl: "https://www.microsoft.com/microsoft-teams",
  },
  {
    slug: "jira",
    category: "collaboration",
    status: "coming-soon",
    type: "partner",
    marketing: true,
    workspace: true,
    iconKey: "jira",
    websiteUrl: "https://www.atlassian.com/software/jira",
    relatedSlugs: ["linear", "slack", "github"],
    keywords: ["Jira localization", "translation issue tracking"],
  },
  {
    slug: "linear",
    category: "collaboration",
    status: "coming-soon",
    type: "partner",
    marketing: true,
    workspace: true,
    iconKey: "linear",
    websiteUrl: "https://linear.app",
    relatedSlugs: ["jira", "slack", "github"],
    keywords: ["Linear localization", "translation workflow Linear"],
  },
  {
    slug: "projects-files",
    category: "tms",
    status: "native",
    type: "native",
    marketing: false,
    workspace: true,
    logoSrc: "/images/logo.png",
    tmsProviderKind: "native",
  },
  {
    slug: "crowdin",
    category: "tms",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/tms/crowdin.png",
    websiteUrl: "https://crowdin.com",
    tmsProviderKind: "crowdin",
    relatedSlugs: ["lokalise", "phrase", "github"],
    keywords: ["Crowdin integration", "Crowdin Hyperlocalise", "TMS connector"],
  },
  {
    slug: "lokalise",
    category: "tms",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/tms/lokalise.webp",
    websiteUrl: "https://lokalise.com",
    tmsProviderKind: "lokalise",
    relatedSlugs: ["crowdin", "phrase", "notion"],
    keywords: ["Lokalise integration", "Lokalise Hyperlocalise"],
  },
  {
    slug: "phrase",
    category: "tms",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/tms/phrase.png",
    websiteUrl: "https://phrase.com",
    tmsProviderKind: "phrase",
    relatedSlugs: ["crowdin", "lokalise", "smartling"],
    keywords: ["Phrase integration", "Phrase TMS Hyperlocalise"],
  },
  {
    slug: "smartling",
    category: "tms",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/tms/smartling.png",
    websiteUrl: "https://www.smartling.com",
    tmsProviderKind: "smartling",
    relatedSlugs: ["phrase", "crowdin"],
    keywords: ["Smartling integration", "enterprise localization TMS"],
  },
  {
    slug: "contentful",
    category: "cms",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/contentful-logo.svg",
    websiteUrl: "https://www.contentful.com",
    relatedSlugs: ["canva", "ahrefs", "semrush"],
    keywords: ["Contentful localization", "CMS translation connector"],
  },
  {
    slug: "canva",
    category: "cms",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/canva-logo.svg",
    websiteUrl: "https://www.canva.com",
    relatedSlugs: ["contentful", "intercom"],
    keywords: ["Canva localization", "design localization connector"],
  },
  {
    slug: "pages",
    category: "cms",
    status: "native",
    type: "native",
    marketing: false,
    workspace: true,
    logoSrc: "/images/logo.png",
  },
  {
    slug: "google-drive",
    category: "guidelines",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    iconKey: "googledrive",
    websiteUrl: "https://drive.google.com",
  },
  {
    slug: "sharepoint",
    category: "guidelines",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    logoSrc: "/images/sharepoint-logo.svg",
    websiteUrl: "https://www.microsoft.com/microsoft-365/sharepoint",
  },
  {
    slug: "notion",
    category: "guidelines",
    status: "coming-soon",
    type: "partner",
    marketing: true,
    workspace: true,
    iconKey: "notion",
    websiteUrl: "https://www.notion.so",
    relatedSlugs: ["lokalise", "contentful"],
    keywords: ["Notion localization guidelines", "style guide import"],
  },
  {
    slug: "intercom",
    category: "customer-engagement",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/intercom-logo.svg",
    websiteUrl: "https://www.intercom.com",
    relatedSlugs: ["contentful", "resend", "slack"],
    keywords: ["Intercom localization", "customer support translation"],
  },
  {
    slug: "braze",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    logoSrc: "/images/braze-logo.svg",
    websiteUrl: "https://www.braze.com",
  },
  {
    slug: "iterable",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    websiteUrl: "https://iterable.com",
  },
  {
    slug: "customer-io",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    logoSrc: "/images/customerio-logo.svg",
    websiteUrl: "https://customer.io",
  },
  {
    slug: "hubspot",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    iconKey: "hubspot",
    websiteUrl: "https://www.hubspot.com",
  },
  {
    slug: "mailchimp",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    iconKey: "mailchimp",
    websiteUrl: "https://mailchimp.com",
  },
  {
    slug: "loops",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    iconKey: "loops",
    websiteUrl: "https://loops.so",
  },
  {
    slug: "sendgrid",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: false,
    workspace: true,
    logoSrc: "/images/sendgrid-logo.svg",
    websiteUrl: "https://sendgrid.com",
  },
  {
    slug: "resend",
    category: "customer-engagement",
    status: "coming-soon",
    type: "partner",
    marketing: true,
    workspace: true,
    iconKey: "resend",
    websiteUrl: "https://resend.com",
    relatedSlugs: ["intercom", "slack"],
    keywords: ["Resend localization", "transactional email translation"],
  },
  {
    slug: "hyperlab",
    category: "experimentation",
    status: "native",
    type: "native",
    marketing: true,
    workspace: true,
    logoSrc: "/images/logo.png",
    relatedSlugs: ["github", "contentful"],
    keywords: ["localization experiments", "Hyperlab", "feature testing localization"],
  },
  {
    slug: "hyperseo",
    category: "seo-tools",
    status: "coming-soon",
    type: "native",
    marketing: false,
    workspace: true,
    logoSrc: "/images/logo.png",
  },
  {
    slug: "ahrefs",
    category: "seo-tools",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/ahrefs-logo.svg",
    websiteUrl: "https://ahrefs.com",
    relatedSlugs: ["semrush", "contentful"],
    keywords: ["Ahrefs localization", "SEO localization workflow"],
  },
  {
    slug: "semrush",
    category: "seo-tools",
    status: "available",
    type: "partner",
    marketing: true,
    workspace: true,
    logoSrc: "/images/semrush-logo.svg",
    websiteUrl: "https://www.semrush.com",
    relatedSlugs: ["ahrefs", "contentful"],
    keywords: ["Semrush localization", "SEO translation workflow"],
  },
];

export const integrationCatalogSlugs = integrationCatalogEntries.map((entry) => entry.slug);

export const marketingIntegrationSlugs = integrationCatalogEntries
  .filter((entry) => entry.marketing)
  .map((entry) => entry.slug) as IntegrationCatalogSlug[];

export function getIntegrationCatalogEntry(slug: string) {
  return integrationCatalogEntries.find((entry) => entry.slug === slug) ?? null;
}

export function getIntegrationCatalogEntriesForWorkspace(
  category?: IntegrationCatalogEntry["category"],
) {
  return integrationCatalogEntries.filter(
    (entry) => entry.workspace && (category ? entry.category === category : true),
  );
}

export function getTmsIntegrationCatalogEntries() {
  return integrationCatalogEntries.filter(
    (entry) => entry.workspace && entry.category === "tms" && entry.tmsProviderKind,
  );
}
