import type { ProjectFileRecord } from "@/api/routes/project/project.schema";

import type { ApiJob } from "../../../jobs/_components/jobs-page-view";
import type { ProjectListRow } from "../../_components/project-list";

export const projectOverviewFixture: ProjectListRow = {
  id: "project_website",
  name: "Website localization",
  key: "website",
  description: "Marketing site and product copy",
  descriptionValue: "Marketing site and product copy",
  translationContext: "Friendly, concise marketing tone",
  translationContextValue: "Friendly, concise marketing tone",
  created: "Jan 12, 2026, 9:30 AM",
  updated: "Mar 18, 2026, 2:15 PM",
  source: "external_tms",
  externalProviderKind: "crowdin",
  externalProjectId: "42",
  sourceLocale: "en-US",
  targetLocales: ["fr-FR", "de-DE", "es-ES"],
  externalProjectUrl: "https://crowdin.com/project/website",
  isActive: true,
  logoUrl: null,
  lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  lastSyncedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  lastSyncErrorAt: null,
  lastSyncErrorMessage: null,
  openJobCount: 2,
};

export const projectOverviewCaughtUpFixture: ProjectListRow = {
  ...projectOverviewFixture,
  openJobCount: 0,
};

export const projectOverviewJobsFixture: ApiJob[] = [
  {
    id: "job_translate_home",
    projectId: "project_website",
    createdByUserId: "user_1",
    kind: "translation",
    type: "file",
    status: "running",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    completedAt: null,
    workflowRunId: null,
    lastError: null,
    inputPayload: { sourceFileId: "marketing/home.json" },
    outcomeKind: null,
    outcomePayload: null,
    reviewCriteria: null,
    reviewTargetLocale: null,
    syncConnectorKind: null,
    syncDirection: null,
    assetType: null,
    assetOperation: null,
    externalProviderKind: null,
    externalTaskId: null,
    externalStatus: null,
    externalTitle: null,
    externalDueDate: null,
    externalTargetLocales: null,
    externalAssignedUsers: null,
    externalSyncState: null,
  },
  {
    id: "job_review_strings",
    projectId: "project_website",
    createdByUserId: "user_1",
    kind: "review",
    type: null,
    status: "waiting_for_review",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completedAt: null,
    workflowRunId: null,
    lastError: null,
    inputPayload: null,
    outcomeKind: null,
    outcomePayload: null,
    reviewCriteria: "Terminology consistency",
    reviewTargetLocale: "fr-FR",
    syncConnectorKind: null,
    syncDirection: null,
    assetType: null,
    assetOperation: null,
    externalProviderKind: null,
    externalTaskId: null,
    externalStatus: null,
    externalTitle: null,
    externalDueDate: null,
    externalTargetLocales: null,
    externalAssignedUsers: null,
    externalSyncState: null,
  },
];

export const projectOverviewFilesFixture: ProjectFileRecord[] = [
  {
    origin: "provider",
    sourcePath: "marketing/home.json",
    sourceHash: null,
    commitSha: null,
    workflowRunId: null,
    uploadedAt: new Date().toISOString(),
    storedFileId: null,
    metadata: {},
    filename: "home.json",
    byteSize: 2048,
    provider: {
      kind: "crowdin",
      resourceType: "file",
      externalProjectId: "42",
      externalResourceId: "101",
      externalUrl: null,
      syncState: "changed",
      sourceLocale: "en-US",
      targetLocales: ["fr-FR", "de-DE"],
      localeReadiness: {
        "fr-FR": "missing",
        "de-DE": "ready",
      },
      revision: null,
      format: "json",
      lastSyncedAt: new Date().toISOString(),
    },
    latestJob: null,
  },
  {
    origin: "repository",
    sourcePath: "marketing/pricing.json",
    sourceHash: "abc123",
    commitSha: "deadbeef",
    workflowRunId: null,
    uploadedAt: new Date().toISOString(),
    storedFileId: "file_1",
    metadata: {},
    filename: "pricing.json",
    byteSize: 1024,
    provider: null,
    latestJob: null,
  },
];
